In [24]:
import pandas as pd
import numpy as np
import time
from matplotlib import pyplot as plt
import seaborn as sns
from countryinfo import CountryInfo

In [25]:
train = pd.read_csv("../data/train/train.csv")
test = pd.read_csv("../data/test/test.csv")

In [26]:
test.head()

,Unnamed: 0,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,month,day
0,47404,2024-06-21,Poland,Austria,1.0,3.0,EURO,Berlin,Germany,True,2024,6,21
1,47405,2024-06-21,Netherlands,France,0.0,0.0,EURO,Leipzig,Germany,True,2024,6,21
2,47406,2024-06-21,Slovakia,Ukraine,1.0,2.0,EURO,Düsseldorf,Germany,True,2024,6,21
3,47408,2024-06-21,Peru,Chile,0.0,0.0,COPA,Arlington,United States,True,2024,6,21
4,47409,2024-06-22,Belgium,Romania,2.0,0.0,EURO,Cologne,Germany,True,2024,6,22

In [27]:
train.drop(columns=['Unnamed: 0'], inplace=True)

In [28]:
train['result'] = np.select(
    [
        train['home_score'] > train['away_score'],
        train['home_score'] < train['away_score']
    ],
    [
        1,  
        2   
    ],
    default=0 
)
test['result'] = np.select(
    [
        test['home_score'] > test['away_score'],
        test['home_score'] < test['away_score']
    ],
    [
        1,  
        2   
    ],
    default=0 
)

In [29]:
train.drop(columns=['home_score', 'away_score'], inplace=True)

## FIFA Rankings

In [30]:
fifa = pd.read_csv('../data/raw/fifa_ranking.csv')
min_date = fifa['rank_date'].min()
train = train[train['date'] >= min_date]

In [31]:

all_teams = pd.concat([train['home_team'], train['away_team']]).unique()

missing_teams = [team for team in all_teams if team not in fifa['country_full'].values]

print(f"Total unique teams in train: {len(all_teams)}")
print(f"Teams NOT found in fifa['country_full']: {len(missing_teams)}")
print(missing_teams)

Total unique teams in train: 147
Teams NOT found in fifa['country_full']: 11
['United States', 'Ivory Coast', 'DR Congo', 'South Korea', 'Czech Republic', 'Iran', 'China', 'North Korea', 'Cape Verde', 'Kyrgyzstan', 'Gambia']

In [32]:
fifa["country_full"] = fifa["country_full"].replace({
    "USA": "United States",
    "Côte d'Ivoire": "Ivory Coast",
    "Congo DR": "DR Congo",
    "Korea Republic": "South Korea",
    "Korea DPR": "North Korea",
    "Czechia": "Czech Republic",
    "IR Iran": "Iran",
    "China PR": "China",
    "Cabo Verde": "Cape Verde",
    "Kyrgyz Republic": "Kyrgyzstan",
    "The Gambia": "Gambia",
})

In [33]:
fifa.head()

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
0,140.0,Brunei Darussalam,BRU,2.0,0.0,140,AFC,1992-12-31
1,33.0,Portugal,POR,38.0,0.0,33,UEFA,1992-12-31
2,32.0,Zambia,ZAM,38.0,0.0,32,CAF,1992-12-31
3,31.0,Greece,GRE,38.0,0.0,31,UEFA,1992-12-31
4,30.0,Algeria,ALG,39.0,0.0,30,CAF,1992-12-31

In [34]:
train = train.sort_index()

In [35]:
fifa["rank_date"] = pd.to_datetime(fifa["rank_date"])
train["date"] = pd.to_datetime(train["date"])

fifa = fifa.sort_values(["country_full", "rank_date"])
train = train.sort_values("date")
test = test.sort_values("date")

home = (
    fifa[["country_full", "rank_date", "total_points"]]
    .rename(columns={
        "country_full": "home_team",
        "rank_date": "date",
        "total_points": "home_points"
    })
    .sort_values(["home_team", "date"])
)

home["date"] = pd.to_datetime(home["date"])

home = home.sort_values(["date", "home_team"]).reset_index(drop=True)

train = train.copy()
train["date"] = pd.to_datetime(train["date"])
train = train.sort_values(["date", "home_team"]).reset_index(drop=True)

train = pd.merge_asof(
    train.sort_values("date"),
    home,
    on="date",
    by="home_team",
    direction="backward"
)

In [36]:
away = (
    fifa[["country_full", "rank_date", "total_points"]]
    .rename(columns={
        "country_full": "away_team",
        "rank_date": "date",
        "total_points": "away_points"
    })
    .sort_values(["away_team", "date"])
)

away["date"] = pd.to_datetime(away["date"])

away = away.sort_values(["date", "away_team"]).reset_index(drop=True)

train = train.copy()
train["date"] = pd.to_datetime(train["date"])
train = train.sort_values(["date", "away_team"]).reset_index(drop=True)

train = pd.merge_asof(
    train.sort_values("date"),
    away,
    on="date",
    by="away_team",
    direction="backward"
)

In [37]:
train.isna().sum()

date            0
home_team       0
away_team       0
tournament      0
city            0
country         0
neutral         0
year            0
month           0
day             0
result          0
home_points     7
away_points    13
dtype: int64

In [38]:
train.dropna(inplace=True)

In [39]:
train.isna().sum()

date           0
home_team      0
away_team      0
tournament     0
city           0
country        0
neutral        0
year           0
month          0
day            0
result         0
home_points    0
away_points    0
dtype: int64

## Location

In [40]:
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

geolocator = Nominatim(
    user_agent="nations-matches-prediction",
    timeout=10
)

geocode = RateLimiter(
    geolocator.geocode,
    min_delay_seconds=2,   # Nominatim requests at most ~1/sec
    max_retries=2,
    error_wait_seconds=5,
    swallow_exceptions=False
)

In [41]:
all_teams = np.unique(train['home_team']).tolist() + np.unique(train['away_team']).tolist()

In [42]:
capitals_cache = {}
capitals_cache["Northern Ireland"] = "Belfast"
capitals_cache["Wales"] = "Cardiff"
capitals_cache["Kosovo"] = "Pristina"
capitals_cache["England"] = "London"

In [43]:
def get_capital(country):
    if country in capitals_cache:
        return capitals_cache[country]
    
    try:
        capital = CountryInfo(country).capital()
        capitals_cache[country] = capital
        return capital
    except Exception as e:
        raise e

In [44]:
train['home_capital'] = train['home_team'].apply(get_capital)
train['away_capital'] = train['away_team'].apply(get_capital)

In [45]:
import json
with open("capitals.json", "w") as f:
    json.dump(capitals_cache, f)

In [46]:
train.isna().sum()

date            0
home_team       0
away_team       0
tournament      0
city            0
country         0
neutral         0
year            0
month           0
day             0
result          0
home_points     0
away_points     0
home_capital    0
away_capital    0
dtype: int64

In [72]:
train['home_comb'] = train['home_capital'] + ", " + train['home_team']
train['away_comb'] = train['away_capital'] + ", " + train['away_team']
train['stadium_comb'] = train['city'] + ", " + train['country']

In [224]:
import time
import json
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderRateLimited

geolocator = Nominatim(
    user_agent="nations-matches-prediction",
    timeout=10
)

CACHE_FILE = "coords_cache.json"

# Load existing cache so you never re-geocode the same place
try:
    with open(CACHE_FILE) as f:
        coords = json.load(f)
except (FileNotFoundError, json.JSONDecodeError):
    coords = {}

def get_coords(place):
    if place in coords:
        return coords[place]  # skip already-geocoded places
    
    for attempt in range(5):
        try:
            time.sleep(1.2)  # always wait before each request
            location = geolocator.geocode(place)
            result = (location.latitude, location.longitude) if location else None
            coords[place] = result

            # Save after every successful call
            with open(CACHE_FILE, "w") as f:
                json.dump(coords, f)

            return result

        except GeocoderRateLimited:
            wait = 60
            print(f"Rate limited on '{place}', waiting {wait}s (attempt {attempt+1}/5)")
            time.sleep(wait)

    print(f"Giving up on '{place}' after 5 attempts")
    coords[place] = None
    return None

places = pd.concat([
    train['home_comb'],
    train['away_comb'],
    train['stadium_comb']
]).dropna().unique()

for place in places:
    result = get_coords(place)
    print(f"{place}: {result}")

Quito, Ecuador: [-0.2201641, -78.5123274]
Bogotá, Colombia: [4.6533817, -74.0836331]
Montevideo, Uruguay: [-34.9058916, -56.1913095]
Buenos Aires, Argentina: [-34.6095579, -58.3887904]
Asunción, Paraguay: [-25.2800459, -57.6343814]
Brasília, Brazil: [-15.7939869, -47.8828]
Washington D.C., United States: [38.8950982, -77.0363849]
Mexico City, Mexico: [19.3207722, -99.1514678]
Santiago, Chile: [-33.4376995, -70.6510671]
Lima, Peru: [-12.0459808, -77.0305912]
Abuja, Nigeria: [9.0643305, 7.4892974]
Tunis, Tunisia: [36.8002068, 10.1857757]
Accra, Ghana: [5.5571096, -0.2012376]
Yamoussoukro, Ivory Coast: [6.8200066, -5.2776034]
Cairo, Egypt: [30.0443879, 31.2357257]
Dakar, Senegal: [14.693425, -17.447938]
Lusaka, Zambia: [-15.4163395, 28.2818414]
Berlin, Germany: [52.5173885, 13.3951309]
Madrid, Spain: [40.416782, -3.703507]
Rome, Italy: [41.8933203, 12.4829321]
Yaoundé, Cameroon: [3.8689867, 11.5213344]
Oslo, Norway: [59.9133301, 10.7389701]
Brussels, Belgium: [50.8467372, 4.352493]
Amsterdam, Netherlands: [52.3730796, 4.8924534]
Bucharest, Romania: [44.4361414, 26.102684]
Seoul, South Korea: [37.5666791, 126.9782914]
Stockholm, Sweden: [59.3251172, 18.0710935]
Riyadh, Saudi Arabia: [24.638916, 46.7160104]
Sofia, Bulgaria: [42.6977028, 23.3217359]
Bern, Switzerland: [46.9484742, 7.4521749]
Sucre, Bolivia: [-19.0477251, -65.2594306]
Moscow, Russia: [55.625578, 37.6063916]
Dublin, Republic of Ireland: [53.3493795, -6.2605593]
Rabat, Morocco: [34.0218454, -6.8408929]
Athens, Greece: [37.9755648, 23.7348324]
Pretoria, South Africa: [-25.7459277, 28.1879101]
Freetown, Sierra Leone: [8.479004, -13.26795]
Libreville, Gabon: [0.4086518, 9.4418849]
Algiers, Algeria: [36.7729333, 3.0588445]
Ouagadougou, Burkina Faso: [12.3681873, -1.5270944]
Maputo, Mozambique: [-25.966213, 32.56745]
Luanda, Angola: [-8.8272699, 13.2439512]
London, England: [51.5074456, -0.1277653]
Copenhagen, Denmark: [55.6867243, 12.5700724]
Ankara, Turkey: [39.9207759, 32.8540497]
Lisbon, Portugal: [38.7077507, -9.1365919]
Prague, Czech Republic: [50.0874654, 14.4212535]
Paris, France: [48.8534951, 2.3483915]
Zagreb, Croatia: [45.8130967, 15.9772795]
Edinburgh, Scotland: [55.9533456, -3.1883749]
Abu Dhabi, United Arab Emirates: [24.4538352, 54.3774014]
Jakarta, Indonesia: [-6.1754049, 106.827168]
Tehran, Iran: [35.6892523, 51.3896004]
Tokyo, Japan: [35.6768601, 139.7638947]
Beijing, China: [39.9057136, 116.3912972]
Bangkok, Thailand: [13.7524938, 100.4935089]
Damascus, Syria: [33.5130695, 36.3095814]
Kuwait City, Kuwait: [29.3796532, 47.9734174]
Baghdad, Iraq: [33.3061701, 44.3872213]
Tashkent, Uzbekistan: [41.3123363, 69.2787079]
Kingston, Jamaica: [17.9712148, -76.7928128]
Kinshasa, DR Congo: [-4.3196982, 15.3424196]
Ljubljana, Slovenia: [46.0500268, 14.5069289]
Beirut, Lebanon: [33.8892265, 35.5025585]
Doha, Qatar: [25.3108807, 51.5081812]
Tegucigalpa, Honduras: [14.1058135, -87.2047053]
Bamako, Mali: [12.6132656, -7.9847391]
Lomé, Togo: [6.130419, 1.215829]
Monrovia, Liberia: [6.3203562, -10.8060492]
San José, Costa Rica: [9.9327707, -84.0796144]
Warsaw, Poland: [52.2319581, 21.0067249]
Harare, Zimbabwe: [-17.8567035, 31.0601584]
Nairobi, Kenya: [-1.2890006, 36.8172812]
Kigali, Rwanda: [-1.9534357, 30.1140089]
Riga, Latvia: [56.9493977, 24.1051846]
Caracas, Venezuela: [10.5060934, -66.9146008]
Manama, Bahrain: [26.2235041, 50.5822436]
Ashgabat, Turkmenistan: [37.9404648, 58.3823487]
Amman, Jordan: [31.9515694, 35.9239625]
Muscat, Oman: [23.6123628, 58.5938134]
Tripoli, Libya: [32.896672, 13.1777923]
Conakry, Guinea: [9.5170602, -13.6998434]
Port of Spain, Trinidad and Tobago: [10.6572678, -61.5180173]
Belgrade, Serbia: [44.8153318, 20.4456588]
Canberra, Australia: [-35.2975906, 149.1012676]
Kyiv, Ukraine: [50.4500336, 30.5241361]
Hanoi, Vietnam: [21.0283334, 105.854041]
Kuala Lumpur, Malaysia: [3.1516964, 101.6942371]
Windhoek, Namibia: [-22.5776104, 17.0772739]
Khartoum, Sudan: [15.5635972, 32.5349123]
Vienna, Austria: [48.2083537, 16.3725042]
Lilongwe, Malawi: [-13.9875107, 33.768144]
Wellington, New Zealand: [-41.2887953, 174.7772114]
Bratislava, Slovakia: [48.1516988, 17.1093063]
Pyongyang, North Korea: [39.0167979, 125.7473609]
New Delhi, India: [28.6138954, 77.2090057]
Malabo, Equatorial Guinea: [3.741877, 8.7740663]
Niamey, Niger: [13.524834, 2.109823]
Gaborone, Botswana: [-24.6581357, 25.9088474]
Praia, Cape Verde: [14.9162811, -23.5095095]
Addis Ababa, Ethiopia: [9.0358119, 38.7524315]
Sarajevo, Bosnia and Herzegovina: [43.8570713, 18.4126147]
Ramallah, Palestine: [31.9158969, 35.1781625]
Brazzaville, Congo: [-4.2694407, 15.2712256]
Port-au-Prince, Haiti: [18.547327, -72.3395928]
Panama City, Panama: [8.9714493, -79.5341802]
Cardiff, Wales: [51.4816546, -3.1791934]
Tirana, Albania: [41.3281482, 19.8184435]
Reykjavik, Iceland: [64.145981, -21.9422367]
Belfast, Northern Ireland: [54.596391, -5.9301829]
Budapest, Hungary: [47.4813896, 19.1457723]
Bissau, Guinea-Bissau: [11.861324, -15.583055]
Kampala, Uganda: [0.3177137, 32.5813539]
Gibraltar, Gibraltar: [36.140807, -5.3541295]
Yerevan, Armenia: [40.1777112, 44.5126233]
Nur-Sultan, Kazakhstan: [51.1282205, 71.4306682]
Baku, Azerbaijan: [40.3755885, 49.8328009]
Tórshavn, Faroe Islands: [62.0101396, -6.7715709]
Vilnius, Lithuania: [54.6870458, 25.2829111]
Minsk, Belarus: [53.9024716, 27.5618225]
Luxembourg, Luxembourg: [49.6112768, 6.129799]
Helsinki, Finland: [60.1666204, 24.9435408]
Tallinn, Estonia: [59.437242, 24.7572693]
Skopje, North Macedonia: [41.9962164, 21.4318935]
Vaduz, Liechtenstein: [47.1392862, 9.5227962]
Tbilisi, Georgia: [41.6934591, 44.8014495]
Nicosia, Cyprus: [35.1746503, 33.3638783]
Podgorica, Montenegro: [42.4415238, 19.2621081]
Andorra la Vella, Andorra: [42.4979185, 1.5032264]
Pristina, Kosovo: [42.6638771, 21.1640849]
Valletta, Malta: [35.8989979, 14.5136607]
City of San Marino, San Marino: [43.9363996, 12.4466991]
Chișinău, Moldova: [47.0245117, 28.8322923]
Jerusalem, Israel: [31.7788472, 35.2257856]
Manila, Philippines: [14.5904492, 120.9803621]
Bishkek, Kyrgyzstan: [42.8761424, 74.6036724]
Sana'a, Yemen: [15.35, 44.2]
Antananarivo, Madagascar: [-18.9100122, 47.5255809]
Nouakchott, Mauritania: [18.0792379, -15.9780071]
Porto-Novo, Benin: [6.4990718, 2.6253361]
Bujumbura, Burundi: [-3.3638125, 29.3675028]
Dodoma, Tanzania: [-6.1791181, 35.7468174]
Moroni, Comoros: [-11.7040306, 43.251909]
Banjul, Gambia: [13.4410165, -16.5627509]
Ottawa, Canada: [45.4208777, -75.6901106]
City of Victoria, Hong Kong: [22.2765855, 114.1693011]
Dushanbe, Tajikistan: [38.5767045, 68.785433]
Machala, Ecuador: [-3.3148937, -79.9512804]
Ambato, Ecuador: [-1.2422413, -78.6287594]
Guayaquil, Ecuador: [-2.1900572, -79.8868669]
Cuenca, Ecuador: [-2.8974072, -79.0041726]
Portoviejo, Ecuador: [-1.05282, -80.4534134]
Sousse, Tunisia: [35.8288284, 10.6405254]
Chicago, United States: [41.8755616, -87.6244212]
Dallas, United States: [32.7762719, -96.7968559]
Pontiac, United States: [42.6389216, -83.2910468]
East Rutherford, United States: [40.833989, -74.0970865]
Pasadena, United States: [34.1476507, -118.144155]
Washington, D.C., United States: [38.8950982, -77.0363849]
Orlando, United States: [28.5421218, -81.379045]
Palo Alto, United States: [37.4443293, -122.1598465]
Foxborough, United States: [42.0653768, -71.2478308]
Maldonado, Uruguay: [-34.9087162, -54.9582718]
Rivera, Uruguay: [-30.900058, -55.5408151]
Paysandú, Uruguay: [-32.3217257, -58.0892136]
Johannesburg, South Africa: [-26.205, 28.049722]
Bloemfontein, South Africa: [-29.116395, 26.215496]
Port Elizabeth, South Africa: [-33.9618598, 25.6186731]
Durban, South Africa: [-29.861825, 31.009909]
Manchester, England: [53.4424618, -2.2324547]
Sheffield, England: [53.3806626, -1.4702278]
Leeds, England: [53.7974185, -1.5437941]
Newcastle, England: [54.9738474, -1.6131572]
Birmingham, England: [52.4948994, -1.8518439]
Nottingham, England: [52.9534193, -1.1496461]
Liverpool, England: [53.3933411, -2.9166389]
Dubai, United Arab Emirates: [25.0742823, 55.1885387]
Al Ain, United Arab Emirates: [24.2248697, 55.7452211]
Cochabamba, Bolivia: [-17.4012458, -66.1675681]
La Paz, Bolivia: [-16.4955455, -68.1336229]
Santa Cruz, Bolivia: [-17.7834217, -63.1820853]
Oruro, Bolivia: [-18.666667, -67.666667]
Bobo Dioulasso, Burkina Faso: [11.1765796, -4.2961436]
Montpellier, France: [43.6112422, 3.8767337]
Saint-Denis, France: [48.9383732, 2.3627508]
Toulouse, France: [43.6044638, 1.4442433]
Bordeaux, France: [44.841225, -0.5800364]
Lens, France: [50.4291723, 2.8319805]
Marseille, France: [43.2963986, 5.3777888]
Nantes, France: [47.2186371, -1.5541362]
Lyon, France: [45.7578137, 4.8320114]
Saint-Étienne, France: [45.4401467, 4.3873058]
Ciudad del Este, Paraguay: [-25.5169015, -54.6168645]
Luque, Paraguay: [-25.2665417, -57.4926928]
Pedro Juan Caballero, Paraguay: [-22.5497781, -55.7384312]
Kumasi, Ghana: [6.6985605, -1.6233086]
Lagos, Nigeria: [6.4550575, 3.3941795]
Kano, Nigeria: [11.9939978, 8.5219738]
Bruges, Belgium: [51.2085526, 3.226772]
Arnhem, Netherlands: [52.0056642, 5.8762345]
Eindhoven, Netherlands: [51.4392648, 5.478633]
Liège, Belgium: [50.6450944, 5.5736112]
Rotterdam, Netherlands: [51.9244424, 4.47775]
Charleroi, Belgium: [50.4116233, 4.444528]
Tripoli, Lebanon: [34.4373616, 35.8348551]
Sidon, Lebanon: [33.564733, 35.374978]
Barranquilla, Colombia: [11.0101922, -74.8231794]
Cali, Colombia: [3.4108435, -76.5812127]
Medellín, Colombia: [6.2697324, -75.6025597]
Armenia, Colombia: [4.4919894, -75.7413961]
Pereira, Colombia: [4.7854606, -75.788322]
Manizales, Colombia: [5.0743694, -75.5081167]
Ségou, Mali: [13.441518, -6.268147]
Sikasso, Mali: [11.529684, -6.8663259]
Mopti, Mali: [14.514489, -3.6464581]
Kayes, Mali: [13.8001844, -10.2245548]
Niigata, Japan: [37.6452283, 138.7669125]
Ulsan, South Korea: [35.5391697, 129.3119136]
Sapporo, Japan: [43.061936, 141.3542924]
Kashima, Japan: [35.9661164, 140.6450292]
Gwangju, South Korea: [35.1558147, 126.8306362]
Busan, South Korea: [35.1799528, 129.0752365]
Saitama, Japan: [35.9754168, 139.4160114]
Kobe, Japan: [34.6932379, 135.1943764]
Suwon, South Korea: [37.2633325, 127.0287472]
Daegu, South Korea: [35.8713, 128.6018]
Jeonju, South Korea: [35.8237631, 127.1472805]
Seogwipo, South Korea: [33.252845, 126.5610278]
Yokohama, Japan: [35.4503381, 139.6343802]
Incheon, South Korea: [37.456, 126.7052]
Rifu, Japan: [38.3301406, 140.9753442]
Ōita, Japan: [33.1819875, 131.4270217]
Fukuroi, Japan: [34.7501492, 137.9246962]
Daejeon, South Korea: [36.3497007, 127.3849016]
Osaka, Japan: [34.6937569, 135.5014539]
Radès, Tunisia: [36.767891, 10.2724617]
Sfax, Tunisia: [34.7394361, 10.7604024]
Bizerte, Tunisia: [37.2720905, 9.8708565]
Monastir, Tunisia: [35.7707582, 10.8280511]
Porto, Portugal: [41.1502195, -8.6103497]
Faro, Portugal: [37.0162944, -7.935182]
Leiria, Portugal: [39.7437902, -8.8071119]
Guimarães, Portugal: [41.4417677, -8.2955712]
Aveiro, Portugal: [40.640496, -8.6537841]
Coimbra, Portugal: [40.2111931, -8.4294632]
Braga, Portugal: [41.5510583, -8.4280045]
Chiclayo, Peru: [-6.7716146, -79.8387175]
Arequipa, Peru: [-16.3988667, -71.5369607]
Trujillo, Peru: [-8.1116778, -79.0287742]
Piura, Peru: [-5.0, -80.333333]
Tacna, Peru: [-18.01386, -70.2511032]
Chengdu, China: [30.659867, 104.063315]
Jinan, China: [36.6519754, 117.1138479]
Chongqing, China: [30.05518, 107.8748712]
Cusco, Peru: [-13.5170887, -71.9785356]
Alexandria, Egypt: [31.1991806, 29.8951716]
Port Said, Egypt: [31.263235, 32.305505]
Ismailia, Egypt: [30.6043775, 32.2770825]
Munich, Germany: [48.1371079, 11.5753822]
Gelsenkirchen, Germany: [51.5110321, 7.0960124]
Dortmund, Germany: [51.5142273, 7.4652789]
Hamburg, Germany: [53.5501721, 10.0013165]
Frankfurt, Germany: [50.1106444, 8.6820917]
Cologne, Germany: [50.938361, 6.959974]
Leipzig, Germany: [51.3406321, 12.3747329]
Nuremberg, Germany: [49.453872, 11.077298]
Hanover, Germany: [52.3744779, 9.7385532]
Kaiserslautern, Germany: [49.4432174, 7.7689951]
Stuttgart, Germany: [48.7784485, 9.1800132]
Mérida, Venezuela: [8.5816963, -71.1658075]
San Cristóbal, Venezuela: [7.7756663, -72.2214154]
Puerto Ordaz, Venezuela: [8.2750351, -62.7558263]
Barinas, Venezuela: [8.1450535, -69.8567392]
Maracaibo, Venezuela: [10.6498095, -71.6443596]
Maturín, Venezuela: [9.7422774, -63.1888854]
Puerto la Cruz, Venezuela: [10.2028617, -64.6307626]
Barquisimeto, Venezuela: [10.0774374, -69.3222293]
Ho Chi Minh City, Vietnam: [10.7737261, 106.7166008]
Palembang, Indonesia: [-2.9888243, 104.7568507]
Shah Alam, Malaysia: [3.0739429, 101.5185278]
Sekondi, Ghana: [4.927456, -1.7490216]
Tamale, Ghana: [9.4051992, -0.8423986]
Basel, Switzerland: [47.5581077, 7.5878261]
Geneva, Switzerland: [46.2017559, 6.1466014]
Klagenfurt, Austria: [46.623943, 14.3075976]
Zürich, Switzerland: [47.3744489, 8.5410422]
Innsbruck, Austria: [47.2654296, 11.3927685]
Salzburg, Austria: [47.7981346, 13.0464806]
Cabinda, Angola: [-5.056395, 12.3211749]
Benguela, Angola: [-12.5790048, 13.4037117]
Lubango, Angola: [-14.9195617, 13.4897509]
Cape Town, South Africa: [-33.9288301, 18.4172197]
Rustenburg, South Africa: [-25.665655, 27.241448]
Polokwane, South Africa: [-23.9058333, 29.4613889]
Nelspruit, South Africa: [-25.4729094, 30.9772719]
Al Rayyan, Qatar: [25.0819602, 51.158416]
La Plata, Argentina: [-34.9206797, -57.9537638]
San Salvador de Jujuy, Argentina: [-24.1852569, -65.2994789]
Santa Fe, Argentina: [-30.3154739, -61.1645076]
San Juan, Argentina: [-30.7054363, -69.1988222]
Mendoza, Argentina: [-34.5970325, -68.7304797]
Salta, Argentina: [-25.2269908, -64.5911956]
Córdoba, Argentina: [-31.4166867, -64.1834193]
Bata, Equatorial Guinea: [2.0064092, 9.9087683]
Franceville, Gabon: [-1.6343979, 13.5894808]
Wrocław, Poland: [51.1089776, 17.0326689]
Kharkiv, Ukraine: [49.9923181, 36.2310146]
Lviv, Ukraine: [49.841952, 24.0315921]
Poznań, Poland: [52.4006632, 16.9197326]
Gdańsk, Poland: [54.4288032, 18.798327]
Donetsk, Ukraine: [47.9212914, 37.7809825]
São Paulo, Brazil: [-23.5506507, -46.6333824]
Cuiabá, Brazil: [-15.5986686, -56.0991301]
Natal, Brazil: [-5.805398, -35.2080905]
Salvador, Brazil: [-12.9822499, -38.4812772]
Fortaleza, Brazil: [-3.7932167, -38.5280359]
Belo Horizonte, Brazil: [-19.9227318, -43.9450948]
Manaus, Brazil: [-3.1316333, -59.9825041]
Recife, Brazil: [-8.0584933, -34.8848193]
Porto Alegre, Brazil: [-30.0324999, -51.2303767]
Rio de Janeiro, Brazil: [-22.9110137, -43.2093727]
Curitiba, Brazil: [-25.4295963, -49.2712724]
Melbourne, Australia: [-37.8142454, 144.9631732]
Sydney, Australia: [-33.8698439, 151.2082848]
Brisbane, Australia: [-27.4689623, 153.0235009]
Newcastle, Australia: [-32.9192953, 151.7795348]
Ebebiyín, Equatorial Guinea: [2.1537363, 11.3370815]
Mongomo, Equatorial Guinea: [1.6282551, 11.3184671]
Viña del Mar, Chile: [-33.0244535, -71.5517636]
La Serena, Chile: [-29.902705, -71.2519575]
Antofagasta, Chile: [-23.6463741, -70.3980033]
Temuco, Chile: [-38.7358908, -72.590538]
Rancagua, Chile: [-34.1702433, -70.740718]
Valparaíso, Chile: [-33.0458456, -71.6196749]
Concepción, Chile: [-36.8270698, -73.0502064]
Santa Clara, United States: [37.2333253, -121.6846349]
Seattle, United States: [47.6038321, -122.330062]
Glendale, United States: [34.1469416, -118.2478471]
Philadelphia, United States: [39.9527237, -75.1635262]
Houston, United States: [29.7589382, -95.3676974]
Villeneuve-d'Ascq, France: [50.6193174, 3.1314002]
Nice, France: [43.7009358, 7.2683912]
Oyem, Gabon: [1.5997904, 11.5751003]
Port-Gentil, Gabon: [-0.7151966, 8.7787919]
Saint Petersburg, Russia: [59.9606739, 30.1586551]
Sochi, Russia: [43.5854823, 39.723109]
Ekaterinburg, Russia: [56.8382071, 60.6007886]
Kaliningrad, Russia: [54.710128, 20.5105838]
Kazan, Russia: [55.7946485, 49.1115022]
Saransk, Russia: [54.18671, 45.18383]
Samara, Russia: [53.1956255, 50.1014927]
Rostov-on-Don, Russia: [47.2610441, 39.7249086]
Volgograd, Russia: [48.7081906, 44.5153353]
Nizhny Novgorod, Russia: [56.3264816, 44.0051395]
Uherské Hradiště, Czech Republic: [49.0681018, 17.4663899]
Astana, Kazakhstan: [51.1282205, 71.4306682]
Trabzon, Turkey: [41.0054605, 39.7301463]
Elbasan, Albania: [41.1126792, 20.0820858]
Ploiești, Romania: [44.9417468, 26.0236504]
Bologna, Italy: [44.4938203, 11.3426327]
Tampere, Finland: [61.4977988, 23.7616335]
St. Gallen, Switzerland: [47.425618, 9.3762397]
Aarhus, Denmark: [56.1496278, 10.2134046]
Attard, Malta: [35.8909172, 14.4430093]
Glasgow, Scotland: [55.861155, -4.2501687]
Serravalle, San Marino: [43.9699026, 12.4802946]
Elche, Spain: [38.2653307, -0.6988391]
Turku, Finland: [60.4515932, 22.2669991]
Zenica, Bosnia and Herzegovina: [44.199828, 17.9093012]
Reykjavík, Iceland: [64.145981, -21.9422367]
Chorzów, Poland: [50.2884726, 18.9703798]
Haifa, Israel: [32.8191218, 34.9983856]
Rijeka, Croatia: [45.3267976, 14.442208]
Trnava, Slovakia: [48.374218, 17.5809299]
Beer Sheva, Israel: [31.2457442, 34.7925181]
Seville, Spain: [37.3886303, -5.9953403]
Milan, Italy: [45.4641943, 9.1896346]
Shkodër, Albania: [42.0681371, 19.5121437]
Konya, Turkey: [37.872734, 32.4924376]
Lucerne, Switzerland: [47.052144, 8.3058123]
Sharjah, United Arab Emirates: [24.9760668, 56.2536044]
Suez, Egypt: [29.974498, 32.537086]
Parma, Italy: [44.6952006, 10.0979869]
Sivas, Turkey: [39.4191717, 37.1012388]
Florence, Italy: [43.7697955, 11.2556404]
Netanya, Israel: [32.3286181, 34.8566246]
Almaty, Kazakhstan: [43.2363924, 76.9457275]
Olomouc, Czech Republic: [49.5940567, 17.251143]
Rimini, Italy: [43.9465433, 12.630749]
Tychy, Poland: [50.114397, 18.9965933]
Istanbul, Turkey: [41.006381, 28.9758715]
Bergamo, Italy: [45.7566557, 9.7542192]
Zaprešić, Croatia: [45.8572728, 15.8050436]
Ta' Qali, Malta: [35.8923492, 14.4196785]
Reggio Emilia, Italy: [44.6086674, 10.5940667]
Plzeň, Czech Republic: [49.7477415, 13.3775249]
Leuven, Belgium: [50.879202, 4.7011675]
Split, Croatia: [43.5116383, 16.4399659]
Goiânia, Brazil: [-16.680882, -49.2532691]
Turin, Italy: [45.0677551, 7.6824892]
Bafoussam, Cameroon: [5.4758844, 10.4217852]
Garoua, Cameroon: [9.3070698, 13.3934527]
Douala, Cameroon: [4.0429389, 9.7062018]
Limbé, Cameroon: [4.010289, 9.207058]
Larnaca, Cyprus: [34.9236095, 33.6236184]
Razgrad, Bulgaria: [43.6394793, 26.7022408]
Novi Sad, Serbia: [45.2551338, 19.8451756]
Osijek, Croatia: [45.5548793, 18.6953685]
Cesena, Italy: [44.136352, 12.2422442]
Vólos, Greece: [39.3624833, 22.9401864]
Mardakan, Azerbaijan: [40.4935881, 50.1495477]
Wolverhampton, England: [52.5847651, -2.127567]
Łódź, Poland: [51.7728245, 19.478486]
Málaga, Spain: [36.7647913, -4.4422005]
İzmir, Turkey: [38.4192537, 27.128469]
Mönchengladbach, Germany: [51.1947131, 6.4353792]
Zaragoza, Spain: [41.6915847, -0.9101268]
Tel Aviv, Israel: [32.0852997, 34.7818064]
Bačka Topola, Serbia: [45.8121657, 19.6304705]
Kraków, Poland: [50.0469432, 19.9971534]
Al Khor, Qatar: [25.7567822, 51.3269839]
Lusail, Qatar: [25.4228888, 51.5197163]
Al Wakrah, Qatar: [25.0037453, 51.4103338]
Enschede, Netherlands: [52.2209855, 6.8940537]
Ebimpé, Ivory Coast: [5.4995714, -4.0800574]
Abidjan, Ivory Coast: [5.320357, -4.016107]
Bouaké, Ivory Coast: [7.6890212, -5.0283552]
Korhogo, Ivory Coast: [9.4580698, -5.6316293]
San-Pédro, Ivory Coast: [4.7589989, -6.6463922]
Faro-Loulé, Portugal: [37.0891428, -8.1168249]
Kaunas, Lithuania: [54.8982139, 23.9044817]
Düsseldorf, Germany: [51.2254018, 6.7763137]
Atlanta, United States: [33.7544657, -84.3898151]

In [225]:
train[['home_lat', 'home_lon']] = (
    train['home_comb']
    .map(coords)
    .apply(pd.Series)
)

train[['away_lat', 'away_lon']] = (
    train['away_comb']
    .map(coords)
    .apply(pd.Series)
)

train[['stadium_lat', 'stadium_lon']] = (
    train['stadium_comb']
    .map(coords)
    .apply(pd.Series)
)

In [226]:
train.head()

,date,home_team,away_team,tournament,city,country,neutral,year,month,day,...,away_capital,home_comb,away_comb,stadium_comb,home_lat,home_lon,away_lat,away_lon,stadium_lat,stadium_lon
0,1993-06-15,Ecuador,Venezuela,COPA,Quito,Ecuador,False,1993,6,15,...,Caracas,"Quito, Ecuador","Caracas, Venezuela","Quito, Ecuador",-0.220164,-78.512327,10.506093,-66.914601,-0.220164,-78.512327
1,1993-06-16,Colombia,Mexico,COPA,Machala,Ecuador,True,1993,6,16,...,Mexico City,"Bogotá, Colombia","Mexico City, Mexico","Machala, Ecuador",4.653382,-74.083633,19.320772,-99.151468,-3.314894,-79.951280
2,1993-06-16,Uruguay,United States,COPA,Ambato,Ecuador,True,1993,6,16,...,Washington D.C.,"Montevideo, Uruguay","Washington D.C., United States","Ambato, Ecuador",-34.905892,-56.191310,38.895098,-77.036385,-1.242241,-78.628759
3,1993-06-17,Argentina,Bolivia,COPA,Guayaquil,Ecuador,True,1993,6,17,...,Sucre,"Buenos Aires, Argentina","Sucre, Bolivia","Guayaquil, Ecuador",-34.609558,-58.388790,-19.047725,-65.259431,-2.190057,-79.886867
4,1993-06-18,Paraguay,Chile,COPA,Cuenca,Ecuador,True,1993,6,18,...,Santiago,"Asunción, Paraguay","Santiago, Chile","Cuenca, Ecuador",-25.280046,-57.634381,-33.437700,-70.651067,-2.897407,-79.004173

In [227]:
def haversine(lat1, lon1, lat2, lon2):
    # Convert degrees to radians
    lat1, lon1, lat2, lon2 = map(
        np.radians, [lat1, lon1, lat2, lon2]
    )

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = (
        np.sin(dlat / 2) ** 2
        + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2) ** 2
    )

    c = 2 * np.arcsin(np.sqrt(a))

    # Earth's radius in kilometers
    R = 6371.0

    return R * c

train["home_stadium_distance_km"] = haversine(
    train["home_lat"],
    train["home_lon"],
    train["stadium_lat"],
    train["stadium_lon"],
)

train["away_stadium_distance_km"] = haversine(
    train["away_lat"],
    train["away_lon"],
    train["stadium_lat"],
    train["stadium_lon"],
)

## Ratings

In [228]:
import asyncio
import pandas as pd
from playwright.async_api import async_playwright
import nest_asyncio
nest_asyncio.apply()


async def make_session():
    playwright = await async_playwright().start()
    browser = await playwright.chromium.launch(headless=True)
    context = await browser.new_context(
        user_agent=(
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0.0.0 Safari/537.36"
        ),
        extra_http_headers={
            "Accept-Language": "en-US,en;q=0.9",
            "Referer": "https://www.sofascore.com/",
        }
    )
    page = await context.new_page()
    print("Warming up browser session...")
    await page.goto("https://www.sofascore.com/", wait_until="domcontentloaded")
    await asyncio.sleep(3)
    return playwright, browser, page


async def search_team_id(page, team_name: str) -> int | None:
    url = f"https://www.sofascore.com/api/v1/search/all?q={team_name.replace(' ', '%20')}&page=0"
    try:
        response = await page.goto(url)
        if response.status != 200:
            print(f"    HTTP {response.status}")
            return None

        data = await response.json()
        results = data.get("results", [])

        # First pass: national teams explicitly flagged
        for r in results:
            if r.get("type") != "team":
                continue
            entity = r["entity"]
            if entity.get("sport", {}).get("slug") != "football":
                continue
            if entity.get("national") is True:
                if team_name.lower() in entity.get("name", "").lower():
                    return entity["id"]

        # Second pass: first football team result
        for r in results:
            if r.get("type") != "team":
                continue
            entity = r["entity"]
            if entity.get("sport", {}).get("slug") == "football":
                return entity["id"]

        return None
    except Exception as e:
        print(f"    Error: {e}")
        return None


async def build_team_id_mapping_async(train: pd.DataFrame) -> dict:
    all_teams = pd.concat([train["home_team"], train["away_team"]]).dropna().unique()
    all_teams = sorted(set(str(t).strip() for t in all_teams))
    print(f"Found {len(all_teams)} unique teams. Looking up IDs...\n")

    playwright, browser, page = await make_session()
    team_id_map = {}
    failed = []

    try:
        for team in all_teams:
            print(f"  Searching: {team} ...", end=" ", flush=True)
            team_id = await search_team_id(page, team)
            if team_id:
                print(f"✓ ID = {team_id}")
                team_id_map[team] = team_id
            else:
                print("✗ Not found")
                failed.append(team)
            await asyncio.sleep(1.5)
    finally:
        await browser.close()
        await playwright.stop()

    with open("team_ids.json", "w") as f:
        json.dump(team_id_map, f, indent=2, ensure_ascii=False)

    print(f"\n✅ Done! {len(team_id_map)}/{len(all_teams)} teams mapped.")
    if failed:
        print(f"⚠️  Not found ({len(failed)}): {failed}")
    return team_id_map


# team_id_map = await build_team_id_mapping_async(train)
# team_id_map['Bosnia and Herzegovina'] = 4479
# team_id_map['Ivory Coast'] = 4768
# team_id_map['Republic of Ireland'] = 4693
# team_id_map['Turkey'] = 4700

In [229]:
with open("team_ids.json", "r") as f:
    team_id_map = json.load(f)

In [231]:
"""
fetch_events_cache.py
---------------------
PASS 1: Fetches all historical events for all 147 national teams and saves
them to a local JSON file (team_events.json) for offline use in pass 2.

Structure of team_events.json:
{
    "4748": [   <- team_id as string key
        {
            "id": 12345,
            "startTimestamp": 1234567890,
            "status": "finished",
            "homeTeamId": 4748,
            "awayTeamId": 4711,
            "homeScore": 2,
            "awayScore": 1,
            "homeRanking": 5,
            "awayRanking": 12,
            "hasStats": true
        },
        ...  sorted descending by startTimestamp (most recent first)
    ],
    ...
}

Progress is saved per team — safe to interrupt and resume.

Requirements:
    pip install playwright nest_asyncio
    python -m playwright install chromium
"""

import asyncio
import json
import nest_asyncio
import datetime as dt
from playwright.async_api import async_playwright

nest_asyncio.apply()

EVENTS_FILE   = "team_events.json"
TEAM_IDS_FILE = "team_ids.json"

# ── Load team ID mapping ───────────────────────────────────────────────────────

with open(TEAM_IDS_FILE, "r") as f:
    TEAM_IDS = json.load(f)  # {team_name: team_id}

# All unique team IDs
ALL_TEAM_IDS = list(set(TEAM_IDS.values()))

# ── Persistence helpers ────────────────────────────────────────────────────────

def load_events_cache() -> dict:
    """Load existing progress from file. Returns {team_id_str: [events]}."""
    try:
        with open(EVENTS_FILE, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}

def save_events_cache(cache: dict):
    """Save full cache to file."""
    with open(EVENTS_FILE, "w") as f:
        json.dump(cache, f)

# ── Browser session ────────────────────────────────────────────────────────────

async def make_session():
    playwright = await async_playwright().start()
    browser = await playwright.chromium.launch(headless=True)
    context = await browser.new_context(
        user_agent=(
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0.0.0 Safari/537.36"
        ),
        extra_http_headers={
            "Accept-Language": "en-US,en;q=0.9",
            "Referer": "https://www.sofascore.com/",
        }
    )
    page = await context.new_page()
    print("Warming up browser session...")
    await page.goto("https://www.sofascore.com/", wait_until="domcontentloaded")
    await asyncio.sleep(3)
    return playwright, browser, page


async def api_get(page, url: str):
    try:
        response = await page.goto(url)
        if response.status == 200:
            return await response.json()
        return None
    except Exception as e:
        print(f"    ⚠ Request failed ({url}): {e}")
        return None

# ── Extract only needed fields from raw event ──────────────────────────────────

def slim_event(event: dict) -> dict:
    """Keep only the fields we need — discard everything else."""
    home = event.get("homeTeam", {})
    away = event.get("awayTeam", {})
    return {
        "id":             event.get("id"),
        "startTimestamp": event.get("startTimestamp"),
        "status":         event.get("status", {}).get("type"),
        "homeTeamId":     home.get("id"),
        "awayTeamId":     away.get("id"),
        "homeScore":      event.get("homeScore", {}).get("current"),
        "awayScore":      event.get("awayScore", {}).get("current"),
        "homeRanking":    home.get("ranking"),
        "awayRanking":    away.get("ranking"),
        "hasStats":       event.get("hasEventPlayerStatistics", False),
    }

# ── Fetch all pages for one team ───────────────────────────────────────────────

async def fetch_all_events_for_team(page, team_id: int) -> list:
    """
    Fetches all pages of events for a team until hasNextPage is False.
    Returns list of slim event dicts sorted descending by startTimestamp.
    """
    all_events = []
    page_num   = 0

    while True:
        url  = f"https://www.sofascore.com/api/v1/team/{team_id}/events/last/{page_num}"
        data = await api_get(page, url)
        await asyncio.sleep(1.2)  # polite delay

        if not data:
            print(f"    ⚠ No data on page {page_num}, stopping.")
            break

        events = data.get("events", [])
        for event in events:
            new_event = slim_event(event)
            if new_event["status"] == "finished":
                all_events.append(new_event)

        print(f"    Page {page_num}: +{len(events)} events (total: {len(all_events)})")

        if not data.get("hasNextPage", False):
            break

        page_num += 1

    # Sort descending by startTimestamp (most recent first)
    all_events.sort(key=lambda e: e.get("startTimestamp", 0), reverse=True)
    return all_events

# ── Main ───────────────────────────────────────────────────────────────────────

async def build_events_cache():
    cache = load_events_cache()

    already_done = set(cache.keys())
    remaining    = [tid for tid in ALL_TEAM_IDS if str(tid) not in already_done]

    print(f"Total teams: {len(ALL_TEAM_IDS)}")
    print(f"Already cached: {len(already_done)}")
    print(f"Remaining: {len(remaining)}\n")

    if not remaining:
        print("✅ All teams already cached. Nothing to do.")
        return cache

    playwright, browser, page = await make_session()

    try:
        for i, team_id in enumerate(remaining):
            # Find team name for display
            team_name = next(
                (name for name, tid in TEAM_IDS.items() if tid == team_id),
                str(team_id)
            )
            print(f"\n[{i+1}/{len(remaining)}] {team_name} (ID: {team_id})")

            events = await fetch_all_events_for_team(page, team_id)
            cache[str(team_id)] = events

            # Save progress after every team
            save_events_cache(cache)
            print(f"  ✅ Saved {len(events)} events for {team_name}")

    finally:
        await browser.close()
        await playwright.stop()

    print(f"\n🎉 Done! {len(cache)} teams cached to {EVENTS_FILE}")
    return cache

In [232]:
cache = await build_events_cache()

Total teams: 145
Already cached: 145
Remaining: 0

✅ All teams already cached. Nothing to do.

In [233]:
"""
fetch_team_ratings.py
---------------------
PASS 2: Uses the pre-built team_events.json (from fetch_events_cache.py)
to look up fixtures and fetch lineup stats on-demand.

Output columns added per team (home_ and away_ prefix):
    fix_1/2/3              — avg starter rating per match
    shots_1/2/3            — total shots by starters per match
    shots_against_1/2/3    — opponent's total shots per match
    scored_1/2/3           — goals scored per match
    conceded_1/2/3         — goals conceded per match (same as opponent scored)
    relative_shots_1/2/3   — shots / (shots + shots_against)
    relative_goals_1/2/3   — scored / (scored + conceded)
    ranking                — FIFA ranking (most recent match)

Requirements:
    pip install playwright nest_asyncio
    python -m playwright install chromium
"""

import asyncio
import json
import math
import pandas as pd
import nest_asyncio
import datetime as dt
from playwright.async_api import async_playwright

nest_asyncio.apply()

# ── Load mappings ──────────────────────────────────────────────────────────────

with open("team_ids.json", "r") as f:
    TEAM_IDS = json.load(f)

with open("team_events.json", "r") as f:
    TEAM_EVENTS = json.load(f)

# ── Output columns ─────────────────────────────────────────────────────────────

MATCH_COLS = ["fix", "shots", "shots_against", "scored", "conceded",
              "relative_shots", "relative_goals"]
N_MATCHES  = 3
ALL_COLS   = (
    [f"home_{col}_{i}" for col in MATCH_COLS for i in range(1, N_MATCHES + 1)] +
    [f"away_{col}_{i}" for col in MATCH_COLS for i in range(1, N_MATCHES + 1)] +
    ["home_ranking", "away_ranking"]
)

EMPTY_STATS = {col: [None] * 3 for col in MATCH_COLS}
EMPTY_STATS["ranking"] = None

# ── Browser session ────────────────────────────────────────────────────────────

async def make_session():
    playwright = await async_playwright().start()
    browser = await playwright.chromium.launch(headless=True)
    context = await browser.new_context(
        user_agent=(
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0.0.0 Safari/537.36"
        ),
        extra_http_headers={
            "Accept-Language": "en-US,en;q=0.9",
            "Referer": "https://www.sofascore.com/",
        }
    )
    page = await context.new_page()
    print("Warming up browser session...")
    await page.goto("https://www.sofascore.com/", wait_until="domcontentloaded")
    await asyncio.sleep(3)
    return playwright, browser, page


async def api_get(page, url: str):
    try:
        response = await page.goto(url)
        if response.status == 200:
            return await response.json()
        return None
    except Exception as e:
        print(f"    ⚠ Request failed ({url}): {e}")
        return None

# ── Fixture lookup (pure offline) ─────────────────────────────────────────────

def fixture_exists_offline(home_id: int, away_id: int, date: dt.date) -> bool:
    day_start = int(dt.datetime(date.year, date.month, date.day, 0, 0, 0).timestamp())
    day_end   = int(dt.datetime(date.year, date.month, date.day, 23, 59, 59).timestamp())

    events = TEAM_EVENTS.get(str(home_id), [])
    for event in events:
        ts = event.get("startTimestamp", 0)
        if ts < day_start - 86400 * 3:
            break
        if day_start <= ts <= day_end:
            h = event.get("homeTeamId")
            a = event.get("awayTeamId")
            if (h == home_id and a == away_id) or (h == away_id and a == home_id):
                return True
    return False


# ── Get last 3 events before timestamp (pure offline) ─────────────────────────

def get_last_3_events(team_id: int, before_timestamp: int) -> list:
    events  = TEAM_EVENTS.get(str(team_id), [])
    results = []
    for event in events:
        if len(results) == 3:
            break
        if event.get("startTimestamp", 0) >= before_timestamp:
            continue
        if event.get("status") != "finished":
            continue
        results.append(event)
    return results


# ── Lineup stats: rating, shots, shots_against — one API call ─────────────────

async def get_lineup_stats(page, event_id: int, team_id: int,
                           home_team_id: int) -> dict:
    """
    Returns {rating, shots, shots_against} for team_id in event_id.
    Both team and opponent stats are extracted in the same call.
    """
    url  = f"https://www.sofascore.com/api/v1/event/{event_id}/lineups"
    data = await api_get(page, url)
    await asyncio.sleep(0.5)

    if not data:
        return {"rating": None, "shots": None, "shots_against": None}

    our_side  = "home" if home_team_id == team_id else "away"
    opp_side  = "away" if our_side == "home" else "home"

    def extract(side: str) -> tuple:
        players = data.get(side, {}).get("players", [])
        ratings, shots = [], 0
        for p in players:
            if p.get("substitute", True):
                continue
            stats = p.get("statistics", {})
            r = stats.get("rating")
            if r is not None:
                try:
                    r = float(r)
                    if not math.isnan(r):
                        ratings.append(r)
                except Exception:
                    pass
            shots += stats.get("totalShots", 0) or 0
        avg_rating = round(sum(ratings) / len(ratings), 3) if ratings else None
        return avg_rating, shots if shots > 0 else None

    our_rating, our_shots = extract(our_side)
    _,          opp_shots = extract(opp_side)

    return {
        "rating":       our_rating,
        "shots":        our_shots,
        "shots_against": opp_shots,
    }


# ── Safe division for relative metrics ────────────────────────────────────────

def safe_ratio(a, b) -> float | None:
    """a / (a + b), returns None if either value is None or sum is 0."""
    if a is None or b is None:
        return None
    total = a + b
    if total == 0:
        return 0.5
    return round(a / total, 4)


# ── Build stats dict for a team from its last 3 events ────────────────────────

async def get_last_3_stats(page, team_id: int, before_timestamp: int) -> dict:
    events  = get_last_3_events(team_id, before_timestamp)
    results = []
    ranking = None

    for event in events:
        # Ranking from most recent match
        if ranking is None:
            if event.get("homeTeamId") == team_id:
                ranking = event.get("homeRanking")
            else:
                ranking = event.get("awayRanking")

        # Goals — always available offline
        if event.get("homeTeamId") == team_id:
            scored   = event.get("homeScore")
            conceded = event.get("awayScore")
        else:
            scored   = event.get("awayScore")
            conceded = event.get("homeScore")

        # Rating + shots + shots_against — one API call if stats exist
        if event.get("hasStats", False):
            lineup = await get_lineup_stats(
                page, event["id"], team_id, event["homeTeamId"]
            )
        else:
            lineup = {"rating": None, "shots": None, "shots_against": None}

        results.append({
            "fix":             lineup["rating"],
            "shots":           lineup["shots"],
            "shots_against":   lineup["shots_against"],
            "scored":          scored,
            "conceded":        conceded,
            "relative_shots":  safe_ratio(lineup["shots"], lineup["shots_against"]),
            "relative_goals":  safe_ratio(scored, conceded),
        })

    # Pad to 3
    while len(results) < 3:
        results.append({col: None for col in MATCH_COLS})

    return {
        **{col: [r[col] for r in results] for col in MATCH_COLS},
        "ranking": ranking,
    }


# ── Cache helpers ──────────────────────────────────────────────────────────────

CACHE_FILE = "ratings_cache.json"

def load_cache() -> dict:
    try:
        with open(CACHE_FILE, "r") as f:
            raw = json.load(f)
            return {tuple(int(x) for x in k.split("_")): v for k, v in raw.items()}
    except FileNotFoundError:
        return {}

def save_cache(cache: dict):
    with open(CACHE_FILE, "w") as f:
        json.dump({f"{k[0]}_{k[1]}": v for k, v in cache.items()}, f)


# ── Main pipeline ──────────────────────────────────────────────────────────────

async def append_ratings_async(train: pd.DataFrame) -> pd.DataFrame:
    df = train.copy()
    for col in ALL_COLS:
        df[col] = None

    playwright, browser, page = await make_session()
    cache = load_cache()
    print(f"✅ Loaded {len(cache)} cached entries")

    try:
        for idx, row in df.iterrows():
            date      = pd.to_datetime(row["date"]).date()
            timestamp = int(dt.datetime(date.year, date.month, date.day).timestamp())

            home_team = str(row["home_team"]).strip()
            away_team = str(row["away_team"]).strip()
            home_id   = TEAM_IDS.get(home_team)
            away_id   = TEAM_IDS.get(away_team)

            print(f"\nRow {idx}: {home_team} vs {away_team} ({date})")

            # ── Missing IDs ──
            if home_id is None or away_id is None:
                print(f"  ⚠ Missing ID — skipping.")
                continue

            home_cache_key = (home_id, timestamp)
            away_cache_key = (away_id, timestamp)
            home_cached    = home_cache_key in cache
            away_cached    = away_cache_key in cache

            if home_cached:
                home_stats = cache[home_cache_key]
                print(f"  Home (cached): {home_team}")
            if away_cached:
                away_stats = cache[away_cache_key]
                print(f"  Away (cached): {away_team}")

            # ── Fixture check (offline) — only if needed ──
            if not home_cached or not away_cached:
                exists = fixture_exists_offline(home_id, away_id, date)
                if not exists:
                    print(f"  ⚠ Fixture not found — caching empty and skipping.")
                    if not home_cached:
                        cache[home_cache_key] = EMPTY_STATS
                        home_stats = EMPTY_STATS
                    if not away_cached:
                        cache[away_cache_key] = EMPTY_STATS
                        away_stats = EMPTY_STATS
                    save_cache(cache)
                    continue
                print(f"  ✓ Fixture confirmed (offline).")

            # ── Fetch stats for uncached teams ──
            if not home_cached:
                home_stats = await get_last_3_stats(page, home_id, timestamp)
                cache[home_cache_key] = home_stats
                save_cache(cache)
                print(f"  Home: {home_team} → fix={home_stats['fix']} shots={home_stats['shots']} shots_against={home_stats['shots_against']} scored={home_stats['scored']} conceded={home_stats['conceded']} rank={home_stats['ranking']}")

            if not away_cached:
                away_stats = await get_last_3_stats(page, away_id, timestamp)
                cache[away_cache_key] = away_stats
                save_cache(cache)
                print(f"  Away: {away_team} → fix={away_stats['fix']} shots={away_stats['shots']} shots_against={away_stats['shots_against']} scored={away_stats['scored']} conceded={away_stats['conceded']} rank={away_stats['ranking']}")

            # ── Write to df copy ──
            for col in MATCH_COLS:
                for i in range(3):
                    df.at[idx, f"home_{col}_{i+1}"] = home_stats[col][i]
                    df.at[idx, f"away_{col}_{i+1}"] = away_stats[col][i]

            df.at[idx, "home_ranking"] = home_stats["ranking"]
            df.at[idx, "away_ranking"] = away_stats["ranking"]

    finally:
        await browser.close()
        await playwright.stop()

    return df


async def run(train: pd.DataFrame) -> pd.DataFrame:
    """Call this with: result = await run(train)"""
    return await append_ratings_async(train)

In [234]:
result = await run(train)

Warming up browser session...
✅ Loaded 4771 cached entries

Row 0: Ecuador vs Venezuela (1993-06-15)
  Home (cached): Ecuador
  Away (cached): Venezuela

Row 1: Colombia vs Mexico (1993-06-16)
  Home (cached): Colombia
  Away (cached): Mexico

Row 2: Uruguay vs United States (1993-06-16)
  Home (cached): Uruguay
  Away (cached): United States

Row 3: Argentina vs Bolivia (1993-06-17)
  Home (cached): Argentina
  Away (cached): Bolivia

Row 4: Paraguay vs Chile (1993-06-18)
  Home (cached): Paraguay
  Away (cached): Chile

Row 5: Brazil vs Peru (1993-06-18)
  Home (cached): Brazil
  Away (cached): Peru

Row 6: Ecuador vs United States (1993-06-19)
  Home (cached): Ecuador
  Away (cached): United States

Row 7: Uruguay vs Venezuela (1993-06-19)
  Home (cached): Uruguay
  Away (cached): Venezuela

Row 8: Argentina vs Mexico (1993-06-20)
  Home (cached): Argentina
  Away (cached): Mexico

Row 9: Colombia vs Bolivia (1993-06-20)
  Home (cached): Colombia
  Away (cached): Bolivia

Row 10: Brazil vs Chile (1993-06-21)
  Home (cached): Brazil
  Away (cached): Chile

Row 11: Paraguay vs Peru (1993-06-21)
  Home (cached): Paraguay
  Away (cached): Peru

Row 12: Ecuador vs Uruguay (1993-06-22)
  Home (cached): Ecuador
  Away (cached): Uruguay

Row 13: United States vs Venezuela (1993-06-22)
  Home (cached): United States
  Away (cached): Venezuela

Row 14: Mexico vs Bolivia (1993-06-23)
  Home (cached): Mexico
  Away (cached): Bolivia

Row 15: Argentina vs Colombia (1993-06-23)
  Home (cached): Argentina
  Away (cached): Colombia

Row 16: Chile vs Peru (1993-06-24)
  Home (cached): Chile
  Away (cached): Peru

Row 17: Brazil vs Paraguay (1993-06-24)
  Home (cached): Brazil
  Away (cached): Paraguay

Row 18: Ecuador vs Paraguay (1993-06-26)
  Home (cached): Ecuador
  Away (cached): Paraguay

Row 19: Colombia vs Uruguay (1993-06-26)
  Home (cached): Colombia
  Away (cached): Uruguay

Row 20: Brazil vs Argentina (1993-06-27)
  Home (cached): Brazil
  Away (cached): Argentina

Row 21: Peru vs Mexico (1993-06-27)
  Home (cached): Peru
  Away (cached): Mexico

Row 22: Ecuador vs Mexico (1993-06-30)
  Home (cached): Ecuador
  Away (cached): Mexico

Row 23: Colombia vs Argentina (1993-07-01)
  Home (cached): Colombia
  Away (cached): Argentina

Row 24: Ecuador vs Colombia (1993-07-03)
  Home (cached): Ecuador
  Away (cached): Colombia

Row 25: Argentina vs Mexico (1993-07-04)
  Home (cached): Argentina
  Away (cached): Mexico

Row 26: Nigeria vs Gabon (1994-03-26)
  Home (cached): Nigeria
  Away (cached): Gabon

Row 27: Tunisia vs Mali (1994-03-26)
  Home (cached): Tunisia
  Away (cached): Mali

Row 28: Ghana vs Guinea (1994-03-27)
  Home (cached): Ghana
  Away (cached): Guinea

Row 29: Ivory Coast vs Sierra Leone (1994-03-27)
  Home (cached): Ivory Coast
  Away (cached): Sierra Leone

Row 31: Egypt vs Gabon (1994-03-28)
  Home (cached): Egypt
  Away (cached): Gabon

Row 32: Senegal vs Guinea (1994-03-29)
  Home (cached): Senegal
  Away (cached): Guinea

Row 33: Zambia vs Sierra Leone (1994-03-29)
  Home (cached): Zambia
  Away (cached): Sierra Leone

Row 34: Nigeria vs Egypt (1994-03-30)
  Home (cached): Nigeria
  Away (cached): Egypt

Row 36: Zambia vs Ivory Coast (1994-03-31)
  Home (cached): Zambia
  Away (cached): Ivory Coast

Row 37: Ghana vs Senegal (1994-03-31)
  Home (cached): Ghana
  Away (cached): Senegal

Row 38: Egypt vs Mali (1994-04-02)
  Home (cached): Egypt
  Away (cached): Mali

Row 40: Ghana vs Ivory Coast (1994-04-03)
  Home (cached): Ghana
  Away (cached): Ivory Coast

Row 41: Zambia vs Senegal (1994-04-03)
  Home (cached): Zambia
  Away (cached): Senegal

Row 42: Zambia vs Mali (1994-04-06)
  Home (cached): Zambia
  Away (cached): Mali

Row 43: Nigeria vs Ivory Coast (1994-04-06)
  Home (cached): Nigeria
  Away (cached): Ivory Coast

Row 44: Ivory Coast vs Mali (1994-04-10)
  Home (cached): Ivory Coast
  Away (cached): Mali

Row 45: Nigeria vs Zambia (1994-04-10)
  Home (cached): Nigeria
  Away (cached): Zambia

Row 46: Germany vs Bolivia (1994-06-17)
  Home (cached): Germany
  Away (cached): Bolivia

Row 47: Spain vs South Korea (1994-06-17)
  Home (cached): Spain
  Away (cached): South Korea

Row 48: United States vs Switzerland (1994-06-18)
  Home (cached): United States
  Away (cached): Switzerland

Row 49: Italy vs Republic of Ireland (1994-06-18)
  Home (cached): Italy
  Away (cached): Republic of Ireland

Row 50: Colombia vs Romania (1994-06-18)
  Home (cached): Colombia
  Away (cached): Romania

Row 51: Cameroon vs Sweden (1994-06-19)
  Home (cached): Cameroon
  Away (cached): Sweden

Row 52: Norway vs Mexico (1994-06-19)
  Home (cached): Norway
  Away (cached): Mexico

Row 53: Belgium vs Morocco (1994-06-19)
  Home (cached): Belgium
  Away (cached): Morocco

Row 54: Brazil vs Russia (1994-06-20)
  Home (cached): Brazil
  Away (cached): Russia

Row 55: Netherlands vs Saudi Arabia (1994-06-20)
  Home (cached): Netherlands
  Away (cached): Saudi Arabia

Row 56: Nigeria vs Bulgaria (1994-06-21)
  Home (cached): Nigeria
  Away (cached): Bulgaria

Row 57: Argentina vs Greece (1994-06-21)
  Home (cached): Argentina
  Away (cached): Greece

Row 58: Germany vs Spain (1994-06-21)
  Home (cached): Germany
  Away (cached): Spain

Row 59: United States vs Colombia (1994-06-22)
  Home (cached): United States
  Away (cached): Colombia

Row 60: Romania vs Switzerland (1994-06-22)
  Home (cached): Romania
  Away (cached): Switzerland

Row 61: South Korea vs Bolivia (1994-06-23)
  Home (cached): South Korea
  Away (cached): Bolivia

Row 62: Italy vs Norway (1994-06-23)
  Home (cached): Italy
  Away (cached): Norway

Row 63: Brazil vs Cameroon (1994-06-24)
  Home (cached): Brazil
  Away (cached): Cameroon

Row 64: Mexico vs Republic of Ireland (1994-06-24)
  Home (cached): Mexico
  Away (cached): Republic of Ireland

Row 65: Sweden vs Russia (1994-06-24)
  Home (cached): Sweden
  Away (cached): Russia

Row 66: Belgium vs Netherlands (1994-06-25)
  Home (cached): Belgium
  Away (cached): Netherlands

Row 67: Saudi Arabia vs Morocco (1994-06-25)
  Home (cached): Saudi Arabia
  Away (cached): Morocco

Row 68: Argentina vs Nigeria (1994-06-25)
  Home (cached): Argentina
  Away (cached): Nigeria

Row 69: Bulgaria vs Greece (1994-06-26)
  Home (cached): Bulgaria
  Away (cached): Greece

Row 70: Switzerland vs Colombia (1994-06-26)
  Home (cached): Switzerland
  Away (cached): Colombia

Row 71: United States vs Romania (1994-06-26)
  Home (cached): United States
  Away (cached): Romania

Row 72: Bolivia vs Spain (1994-06-27)
  Home (cached): Bolivia
  Away (cached): Spain

Row 73: Germany vs South Korea (1994-06-27)
  Home (cached): Germany
  Away (cached): South Korea

Row 74: Russia vs Cameroon (1994-06-28)
  Home (cached): Russia
  Away (cached): Cameroon

Row 75: Italy vs Mexico (1994-06-28)
  Home (cached): Italy
  Away (cached): Mexico

Row 76: Republic of Ireland vs Norway (1994-06-28)
  Home (cached): Republic of Ireland
  Away (cached): Norway

Row 77: Brazil vs Sweden (1994-06-28)
  Home (cached): Brazil
  Away (cached): Sweden

Row 78: Morocco vs Netherlands (1994-06-29)
  Home (cached): Morocco
  Away (cached): Netherlands

Row 79: Belgium vs Saudi Arabia (1994-06-29)
  Home (cached): Belgium
  Away (cached): Saudi Arabia

Row 80: Greece vs Nigeria (1994-06-30)
  Home (cached): Greece
  Away (cached): Nigeria

Row 81: Argentina vs Bulgaria (1994-06-30)
  Home (cached): Argentina
  Away (cached): Bulgaria

Row 82: Germany vs Belgium (1994-07-02)
  Home (cached): Germany
  Away (cached): Belgium

Row 83: Spain vs Switzerland (1994-07-02)
  Home (cached): Spain
  Away (cached): Switzerland

Row 84: Romania vs Argentina (1994-07-03)
  Home (cached): Romania
  Away (cached): Argentina

Row 85: Saudi Arabia vs Sweden (1994-07-03)
  Home (cached): Saudi Arabia
  Away (cached): Sweden

Row 86: United States vs Brazil (1994-07-04)
  Home (cached): United States
  Away (cached): Brazil

Row 87: Netherlands vs Republic of Ireland (1994-07-04)
  Home (cached): Netherlands
  Away (cached): Republic of Ireland

Row 88: Nigeria vs Italy (1994-07-05)
  Home (cached): Nigeria
  Away (cached): Italy

Row 89: Mexico vs Bulgaria (1994-07-05)
  Home (cached): Mexico
  Away (cached): Bulgaria

Row 90: Italy vs Spain (1994-07-09)
  Home (cached): Italy
  Away (cached): Spain

Row 91: Netherlands vs Brazil (1994-07-09)
  Home (cached): Netherlands
  Away (cached): Brazil

Row 92: Bulgaria vs Germany (1994-07-10)
  Home (cached): Bulgaria
  Away (cached): Germany

Row 93: Romania vs Sweden (1994-07-10)
  Home (cached): Romania
  Away (cached): Sweden

Row 94: Sweden vs Brazil (1994-07-13)
  Home (cached): Sweden
  Away (cached): Brazil

Row 95: Bulgaria vs Italy (1994-07-13)
  Home (cached): Bulgaria
  Away (cached): Italy

Row 96: Sweden vs Bulgaria (1994-07-16)
  Home (cached): Sweden
  Away (cached): Bulgaria

Row 97: Brazil vs Italy (1994-07-17)
  Home (cached): Brazil
  Away (cached): Italy

Row 98: Uruguay vs Venezuela (1995-07-05)
  Home (cached): Uruguay
  Away (cached): Venezuela

Row 99: Mexico vs Paraguay (1995-07-06)
  Home (cached): Mexico
  Away (cached): Paraguay

Row 100: Colombia vs Peru (1995-07-07)
  Home (cached): Colombia
  Away (cached): Peru

Row 101: Brazil vs Ecuador (1995-07-07)
  Home (cached): Brazil
  Away (cached): Ecuador

Row 102: Argentina vs Bolivia (1995-07-08)
  Home (cached): Argentina
  Away (cached): Bolivia

Row 103: United States vs Chile (1995-07-08)
  Home (cached): United States
  Away (cached): Chile

Row 104: Uruguay vs Paraguay (1995-07-09)
  Home (cached): Uruguay
  Away (cached): Paraguay

Row 105: Mexico vs Venezuela (1995-07-09)
  Home (cached): Mexico
  Away (cached): Venezuela

Row 106: Colombia vs Ecuador (1995-07-10)
  Home (cached): Colombia
  Away (cached): Ecuador

Row 107: Brazil vs Peru (1995-07-10)
  Home (cached): Brazil
  Away (cached): Peru

Row 108: Argentina vs Chile (1995-07-11)
  Home (cached): Argentina
  Away (cached): Chile

Row 109: United States vs Bolivia (1995-07-11)
  Home (cached): United States
  Away (cached): Bolivia

Row 110: Paraguay vs Venezuela (1995-07-12)
  Home (cached): Paraguay
  Away (cached): Venezuela

Row 111: Brazil vs Colombia (1995-07-13)
  Home (cached): Brazil
  Away (cached): Colombia

Row 112: Peru vs Ecuador (1995-07-13)
  Home (cached): Peru
  Away (cached): Ecuador

Row 113: Uruguay vs Mexico (1995-07-13)
  Home (cached): Uruguay
  Away (cached): Mexico

Row 114: Chile vs Bolivia (1995-07-14)
  Home (cached): Chile
  Away (cached): Bolivia

Row 115: Argentina vs United States (1995-07-14)
  Home (cached): Argentina
  Away (cached): United States

Row 116: Uruguay vs Bolivia (1995-07-16)
  Home (cached): Uruguay
  Away (cached): Bolivia

Row 117: Paraguay vs Colombia (1995-07-16)
  Home (cached): Paraguay
  Away (cached): Colombia

Row 118: United States vs Mexico (1995-07-17)
  Home (cached): United States
  Away (cached): Mexico

Row 119: Brazil vs Argentina (1995-07-17)
  Home (cached): Brazil
  Away (cached): Argentina

Row 120: Uruguay vs Colombia (1995-07-19)
  Home (cached): Uruguay
  Away (cached): Colombia

Row 121: United States vs Brazil (1995-07-20)
  Home (cached): United States
  Away (cached): Brazil

Row 122: Colombia vs United States (1995-07-22)
  Home (cached): Colombia
  Away (cached): United States

Row 123: Uruguay vs Brazil (1995-07-23)
  Home (cached): Uruguay
  Away (cached): Brazil

Row 124: South Africa vs Cameroon (1996-01-13)
  Home (cached): South Africa
  Away (cached): Cameroon

Row 125: Zambia vs Algeria (1996-01-14)
  Home (cached): Zambia
  Away (cached): Algeria

Row 126: Ivory Coast vs Ghana (1996-01-14)
  Home (cached): Ivory Coast
  Away (cached): Ghana

Row 127: Sierra Leone vs Burkina Faso (1996-01-15)
  Home (cached): Sierra Leone
  Away (cached): Burkina Faso

Row 128: Egypt vs Angola (1996-01-15)
  Home (cached): Egypt
  Away (cached): Angola

Row 129: Gabon vs Liberia (1996-01-16)
  Home (cached): Gabon
  Away (cached): Liberia

Row 130: Tunisia vs Mozambique (1996-01-16)
  Home (cached): Tunisia
  Away (cached): Mozambique

Row 131: Cameroon vs Egypt (1996-01-18)
  Home (cached): Cameroon
  Away (cached): Egypt

Row 132: Algeria vs Sierra Leone (1996-01-18)
  Home (cached): Algeria
  Away (cached): Sierra Leone

Row 134: Ghana vs Tunisia (1996-01-19)
  Home (cached): Ghana
  Away (cached): Tunisia

Row 135: South Africa vs Angola (1996-01-20)
  Home (cached): South Africa
  Away (cached): Angola

Row 136: Burkina Faso vs Zambia (1996-01-20)
  Home (cached): Burkina Faso
  Away (cached): Zambia

Row 137: Mozambique vs Ivory Coast (1996-01-21)
  Home (cached): Mozambique
  Away (cached): Ivory Coast

Row 138: Burkina Faso vs Algeria (1996-01-24)
  Home (cached): Burkina Faso
  Away (cached): Algeria

Row 139: Angola vs Cameroon (1996-01-24)
  Home (cached): Angola
  Away (cached): Cameroon

Row 140: South Africa vs Egypt (1996-01-24)
  Home (cached): South Africa
  Away (cached): Egypt

Row 141: Sierra Leone vs Zambia (1996-01-24)
  Home (cached): Sierra Leone
  Away (cached): Zambia

Row 143: Mozambique vs Ghana (1996-01-25)
  Home (cached): Mozambique
  Away (cached): Ghana

Row 144: Tunisia vs Ivory Coast (1996-01-25)
  Home (cached): Tunisia
  Away (cached): Ivory Coast

Row 145: South Africa vs Algeria (1996-01-27)
  Home (cached): South Africa
  Away (cached): Algeria

Row 146: Zambia vs Egypt (1996-01-27)
  Home (cached): Zambia
  Away (cached): Egypt

Row 147: Gabon vs Tunisia (1996-01-28)
  Home (cached): Gabon
  Away (cached): Tunisia

Row 149: South Africa vs Ghana (1996-01-31)
  Home (cached): South Africa
  Away (cached): Ghana

Row 150: Zambia vs Tunisia (1996-01-31)
  Home (cached): Zambia
  Away (cached): Tunisia

Row 151: Zambia vs Ghana (1996-02-03)
  Home (cached): Zambia
  Away (cached): Ghana

Row 152: South Africa vs Tunisia (1996-02-03)
  Home (cached): South Africa
  Away (cached): Tunisia

Row 153: England vs Switzerland (1996-06-08)
  Home (cached): England
  Away (cached): Switzerland

Row 154: Germany vs Czech Republic (1996-06-09)
  Home (cached): Germany
  Away (cached): Czech Republic

Row 155: Denmark vs Portugal (1996-06-09)
  Home (cached): Denmark
  Away (cached): Portugal

Row 156: Spain vs Bulgaria (1996-06-09)
  Home (cached): Spain
  Away (cached): Bulgaria

Row 157: Romania vs France (1996-06-10)
  Home (cached): Romania
  Away (cached): France

Row 158: Netherlands vs Scotland (1996-06-10)
  Home (cached): Netherlands
  Away (cached): Scotland

Row 159: Turkey vs Croatia (1996-06-11)
  Home (cached): Turkey
  Away (cached): Croatia

Row 160: Italy vs Russia (1996-06-11)
  Home (cached): Italy
  Away (cached): Russia

Row 161: Switzerland vs Netherlands (1996-06-13)
  Home (cached): Switzerland
  Away (cached): Netherlands

Row 162: Bulgaria vs Romania (1996-06-13)
  Home (cached): Bulgaria
  Away (cached): Romania

Row 163: Portugal vs Turkey (1996-06-14)
  Home (cached): Portugal
  Away (cached): Turkey

Row 164: Czech Republic vs Italy (1996-06-14)
  Home (cached): Czech Republic
  Away (cached): Italy

Row 165: France vs Spain (1996-06-15)
  Home (cached): France
  Away (cached): Spain

Row 166: England vs Scotland (1996-06-15)
  Home (cached): England
  Away (cached): Scotland

Row 167: Croatia vs Denmark (1996-06-16)
  Home (cached): Croatia
  Away (cached): Denmark

Row 168: Russia vs Germany (1996-06-16)
  Home (cached): Russia
  Away (cached): Germany

Row 169: France vs Bulgaria (1996-06-18)
  Home (cached): France
  Away (cached): Bulgaria

Row 170: England vs Netherlands (1996-06-18)
  Home (cached): England
  Away (cached): Netherlands

Row 171: Romania vs Spain (1996-06-18)
  Home (cached): Romania
  Away (cached): Spain

Row 172: Scotland vs Switzerland (1996-06-18)
  Home (cached): Scotland
  Away (cached): Switzerland

Row 173: Croatia vs Portugal (1996-06-19)
  Home (cached): Croatia
  Away (cached): Portugal

Row 174: Italy vs Germany (1996-06-19)
  Home (cached): Italy
  Away (cached): Germany

Row 175: Russia vs Czech Republic (1996-06-19)
  Home (cached): Russia
  Away (cached): Czech Republic

Row 176: Turkey vs Denmark (1996-06-19)
  Home (cached): Turkey
  Away (cached): Denmark

Row 177: France vs Netherlands (1996-06-22)
  Home (cached): France
  Away (cached): Netherlands

Row 178: England vs Spain (1996-06-22)
  Home (cached): England
  Away (cached): Spain

Row 179: Germany vs Croatia (1996-06-23)
  Home (cached): Germany
  Away (cached): Croatia

Row 180: Czech Republic vs Portugal (1996-06-23)
  Home (cached): Czech Republic
  Away (cached): Portugal

Row 181: England vs Germany (1996-06-26)
  Home (cached): England
  Away (cached): Germany

Row 182: France vs Czech Republic (1996-06-26)
  Home (cached): France
  Away (cached): Czech Republic

Row 183: Czech Republic vs Germany (1996-06-30)
  Home (cached): Czech Republic
  Away (cached): Germany

Row 184: United Arab Emirates vs South Korea (1996-12-04)
  Home (cached): United Arab Emirates
  Away (cached): South Korea

Row 185: Indonesia vs Kuwait (1996-12-04)
  Home (cached): Indonesia
  Away (cached): Kuwait

Row 186: Iran vs Iraq (1996-12-05)
  Home (cached): Iran
  Away (cached): Iraq

Row 187: Saudi Arabia vs Thailand (1996-12-05)
  Home (cached): Saudi Arabia
  Away (cached): Thailand

Row 188: Japan vs Syria (1996-12-06)
  Home (cached): Japan
  Away (cached): Syria

Row 189: China vs Uzbekistan (1996-12-06)
  Home (cached): China
  Away (cached): Uzbekistan

Row 190: South Korea vs Indonesia (1996-12-07)
  Home (cached): South Korea
  Away (cached): Indonesia

Row 191: United Arab Emirates vs Kuwait (1996-12-07)
  Home (cached): United Arab Emirates
  Away (cached): Kuwait

Row 192: Saudi Arabia vs Iraq (1996-12-08)
  Home (cached): Saudi Arabia
  Away (cached): Iraq

Row 193: Thailand vs Iran (1996-12-08)
  Home (cached): Thailand
  Away (cached): Iran

Row 194: Syria vs China (1996-12-09)
  Home (cached): Syria
  Away (cached): China

Row 195: Japan vs Uzbekistan (1996-12-09)
  Home (cached): Japan
  Away (cached): Uzbekistan

Row 196: United Arab Emirates vs Indonesia (1996-12-10)
  Home (cached): United Arab Emirates
  Away (cached): Indonesia

Row 197: Kuwait vs South Korea (1996-12-10)
  Home (cached): Kuwait
  Away (cached): South Korea

Row 198: Saudi Arabia vs Iran (1996-12-11)
  Home (cached): Saudi Arabia
  Away (cached): Iran

Row 199: Iraq vs Thailand (1996-12-11)
  Home (cached): Iraq
  Away (cached): Thailand

Row 200: Uzbekistan vs Syria (1996-12-12)
  Home (cached): Uzbekistan
  Away (cached): Syria

Row 201: Japan vs China (1996-12-12)
  Home (cached): Japan
  Away (cached): China

Row 202: Kuwait vs Japan (1996-12-15)
  Home (cached): Kuwait
  Away (cached): Japan

Row 203: United Arab Emirates vs Iraq (1996-12-15)
  Home (cached): United Arab Emirates
  Away (cached): Iraq

Row 204: Saudi Arabia vs China (1996-12-16)
  Home (cached): Saudi Arabia
  Away (cached): China

Row 205: South Korea vs Iran (1996-12-16)
  Home (cached): South Korea
  Away (cached): Iran

Row 206: United Arab Emirates vs Kuwait (1996-12-19)
  Home (cached): United Arab Emirates
  Away (cached): Kuwait

Row 207: Iran vs Saudi Arabia (1996-12-19)
  Home (cached): Iran
  Away (cached): Saudi Arabia

Row 208: Iran vs Kuwait (1996-12-21)
  Home (cached): Iran
  Away (cached): Kuwait

Row 209: United Arab Emirates vs Saudi Arabia (1996-12-21)
  Home (cached): United Arab Emirates
  Away (cached): Saudi Arabia

Row 210: Argentina vs Ecuador (1997-06-11)
  Home (cached): Argentina
  Away (cached): Ecuador

Row 211: Chile vs Paraguay (1997-06-11)
  Home (cached): Chile
  Away (cached): Paraguay

Row 212: Peru vs Uruguay (1997-06-12)
  Home (cached): Peru
  Away (cached): Uruguay

Row 213: Bolivia vs Venezuela (1997-06-12)
  Home (cached): Bolivia
  Away (cached): Venezuela

Row 214: Mexico vs Colombia (1997-06-13)
  Home (cached): Mexico
  Away (cached): Colombia

Row 215: Brazil vs Costa Rica (1997-06-13)
  Home (cached): Brazil
  Away (cached): Costa Rica


In [241]:
result.isna().sum()

date                        0
home_team                   0
away_team                   0
tournament                  0
city                        0
country                     0
neutral                     0
year                        0
month                       0
day                         0
result                      0
home_points                 0
away_points                 0
home_capital                0
away_capital                0
home_comb                   0
away_comb                   0
stadium_comb                0
home_lat                    0
home_lon                    0
away_lat                    0
away_lon                    0
stadium_lat                 0
stadium_lon                 0
home_stadium_distance_km    0
away_stadium_distance_km    0
home_fix_1                  0
home_fix_2                  0
home_shots_1                3
home_shots_2                3
home_shots_against_1        4
home_shots_against_2        2
home_scored_1               0
home_scored_2               0
home_conceded_1             0
home_conceded_2             0
home_relative_shots_1       7
home_relative_shots_2       5
home_relative_goals_1       0
home_relative_goals_2       0
away_fix_1                  0
away_fix_2                  0
away_shots_1                0
away_shots_2                1
away_shots_against_1        0
away_shots_against_2        3
away_scored_1               0
away_scored_2               0
away_conceded_1             0
away_conceded_2             0
away_relative_shots_1       0
away_relative_shots_2       4
away_relative_goals_1       0
away_relative_goals_2       0
home_ranking                0
away_ranking                0
dtype: int64

In [240]:
result.shape

(897, 56)

In [237]:
import re

fix_cols = ["home_fix_1", "home_fix_2", "home_fix_3"]

result = result[result[fix_cols].notna().sum(axis=1) >= 2].copy()

groups = {}

for col in result.columns:
    m = re.match(r"home_(.+)_(1|2|3)$", col)
    if m:
        base = m.group(1)
        groups.setdefault(base, {})[int(m.group(2))] = col

groups = {
    base: [cols[1], cols[2], cols[3]]
    for base, cols in groups.items()
    if all(i in cols for i in (1, 2, 3))
}

# Process each row
for idx in result.index:
    keep = (
        result.loc[idx, fix_cols]
        .notna()
        .to_numpy()
        .nonzero()[0][:2] + 1      
    )

    for base, cols in groups.items():
        values = [result.at[idx, cols[pos - 1]] for pos in keep]

        result.at[idx, cols[0]] = values[0]
        result.at[idx, cols[1]] = values[1]

# Drop every *_3 column
cols_to_drop = [cols[2] for cols in groups.values()]
result = result.drop(columns=cols_to_drop)

In [239]:
fix_cols = ["away_fix_1", "away_fix_2", "away_fix_3"]

result = result[result[fix_cols].notna().sum(axis=1) >= 2].copy()

groups = {}

for col in result.columns:
    m = re.match(r"away_(.+)_(1|2|3)$", col)
    if m:
        base = m.group(1)
        groups.setdefault(base, {})[int(m.group(2))] = col

groups = {
    base: [cols[1], cols[2], cols[3]]
    for base, cols in groups.items()
    if all(i in cols for i in (1, 2, 3))
}

# Process each row
for idx in result.index:
    keep = (
        result.loc[idx, fix_cols]
        .notna()
        .to_numpy()
        .nonzero()[0][:2] + 1      
    )

    for base, cols in groups.items():
        values = [result.at[idx, cols[pos - 1]] for pos in keep]

        result.at[idx, cols[0]] = values[0]
        result.at[idx, cols[1]] = values[1]

# Drop every *_3 column
cols_to_drop = [cols[2] for cols in groups.values()]
result = result.drop(columns=cols_to_drop)

In [242]:
result.dropna(inplace=True)

## Weather

In [243]:
import requests

def get_weather_url(lat, lon, date):
        
    try:
        history = requests.get(
            "https://archive-api.open-meteo.com/v1/archive",
            params={
                    "latitude": lat,
                    "longitude": lon,
                    "start_date": date,
                    "end_date": date,
                    "daily": "temperature_2m_max,temperature_2m_min,precipitation_sum,wind_speed_10m_max",
                    "timezone": "auto"
                }
            ).json()
        return {
            'temperature_max' : history['daily']['temperature_2m_max'][0],
            'temperature_min' : history['daily']['temperature_2m_min'][0],
            'precipitation' : history['daily']['precipitation_sum'][0],
            'wind_speed' : history['daily']['wind_speed_10m_max'][0]
        }
    except:
        raise Exception(f"Error for {lat}, {lon}, {date}")

In [ ]:
import json

CACHE_FILE = "weather_cache.json"

# Load cache
try:
    with open(CACHE_FILE) as f:
        weather = json.load(f)
except FileNotFoundError:
    weather = {}

def cache_key(lat, lon, date):
    return f"{lat}_{lon}_{date}"  

def get_weather(lat, lon, date):
    key = cache_key(lat, lon, date)
    
    if key in weather:
        print(f"Cache hit for {key}")
        return weather[key]  

    for attempt in range(5):
        try:
            time.sleep(1.2)  # respect 600/min limit (~1 req/sec)
            result = get_weather_url(lat, lon, date)

            weather[key] = result
            print("result is back for ", (lon, lat, date))
            with open(CACHE_FILE, "w") as f:
                json.dump(weather, f)

            return result

        except Exception as e:
            wait = 60
            print(f"Error: {e}, waiting {wait}s (attempt {attempt+1}/5)")
            time.sleep(wait)

    print(f"Giving up on ({lat}, {lon}, {date}) after 5 attempts")
    weather[key] = None
    return None

In [253]:
result["date"] = result["date"].dt.date

In [254]:

unique = result[['home_lat', 'home_lon', 'date']].drop_duplicates()

unique['weather'] = unique.apply(
    lambda row: get_weather(row['home_lat'], row['home_lon'], row['date']),
    axis=1
)

weather_df = unique['weather'].apply(pd.Series).add_prefix("home_")
unique = pd.concat([unique, weather_df], axis=1).drop(columns='weather')

result = result.merge(unique, on=['home_lat', 'home_lon', 'date'], how='left')

1994-06-18
Cache hit for 41.8933203_12.4829321_1994-06-18
1994-06-19
Cache hit for 50.8467372_4.352493_1994-06-19
1994-06-21
Cache hit for -34.6095579_-58.3887904_1994-06-21
1994-06-21
Cache hit for 52.5173885_13.3951309_1994-06-21
1994-06-22
Cache hit for 44.4361414_26.102684_1994-06-22
1994-06-24
Cache hit for -15.7939869_-47.8828_1994-06-24
1994-06-24
Cache hit for 19.3207722_-99.1514678_1994-06-24
1994-06-25
Cache hit for 50.8467372_4.352493_1994-06-25
1994-06-26
Cache hit for 42.6977028_23.3217359_1994-06-26
1994-06-26
Cache hit for 46.9484742_7.4521749_1994-06-26
1994-06-27
Cache hit for -19.0477251_-65.2594306_1994-06-27
1994-06-27
Cache hit for 52.5173885_13.3951309_1994-06-27
1994-06-28
Cache hit for 55.625578_37.6063916_1994-06-28
1994-06-28
Cache hit for 41.8933203_12.4829321_1994-06-28
1994-06-28
Cache hit for 53.3493795_-6.2605593_1994-06-28
1994-06-28
Cache hit for -15.7939869_-47.8828_1994-06-28
1994-06-29
Cache hit for 34.0218454_-6.8408929_1994-06-29
1994-06-29
Cache hit for 50.8467372_4.352493_1994-06-29
1994-07-02
Cache hit for 52.5173885_13.3951309_1994-07-02
1994-07-02
Cache hit for 40.416782_-3.703507_1994-07-02
1994-07-03
Cache hit for 44.4361414_26.102684_1994-07-03
1994-07-03
Cache hit for 24.638916_46.7160104_1994-07-03
1994-07-04
Cache hit for 52.3730796_4.8924534_1994-07-04
1994-07-05
Cache hit for 9.0643305_7.4892974_1994-07-05
1994-07-05
Cache hit for 19.3207722_-99.1514678_1994-07-05
1994-07-09
Cache hit for 41.8933203_12.4829321_1994-07-09
1994-07-09
Cache hit for 52.3730796_4.8924534_1994-07-09
1994-07-10
Cache hit for 42.6977028_23.3217359_1994-07-10
1994-07-10
Cache hit for 44.4361414_26.102684_1994-07-10
1994-07-13
Cache hit for 42.6977028_23.3217359_1994-07-13
1994-07-16
Cache hit for 59.3251172_18.0710935_1994-07-16
1994-07-17
Cache hit for -15.7939869_-47.8828_1994-07-17
1996-06-08
result is back for  (-0.1277653, 51.5074456, datetime.date(1996, 6, 8))
1996-06-09
Cache hit for 55.6867243_12.5700724_1996-06-09
1996-06-09
Cache hit for 40.416782_-3.703507_1996-06-09
1996-06-10
Cache hit for 44.4361414_26.102684_1996-06-10
1996-06-10
Cache hit for 52.3730796_4.8924534_1996-06-10
1996-06-11
Cache hit for 41.8933203_12.4829321_1996-06-11
1996-06-13
Cache hit for 46.9484742_7.4521749_1996-06-13
1996-06-13
Cache hit for 42.6977028_23.3217359_1996-06-13
1996-06-15
Cache hit for 48.8534951_2.3483915_1996-06-15
1996-06-15
result is back for  (-0.1277653, 51.5074456, datetime.date(1996, 6, 15))
1996-06-16
Cache hit for 55.625578_37.6063916_1996-06-16
1996-06-18
Cache hit for 48.8534951_2.3483915_1996-06-18
1996-06-18
result is back for  (-0.1277653, 51.5074456, datetime.date(1996, 6, 18))
1996-06-18
Cache hit for 44.4361414_26.102684_1996-06-18
1996-06-18
Cache hit for 55.9533456_-3.1883749_1996-06-18
1996-06-19
Cache hit for 45.8130967_15.9772795_1996-06-19
1996-06-19
Cache hit for 41.8933203_12.4829321_1996-06-19
1996-06-19
Cache hit for 55.625578_37.6063916_1996-06-19
1996-06-19
Cache hit for 39.9207759_32.8540497_1996-06-19
1996-06-22
Cache hit for 48.8534951_2.3483915_1996-06-22
1996-06-22
result is back for  (-0.1277653, 51.5074456, datetime.date(1996, 6, 22))
1996-06-23
Cache hit for 52.5173885_13.3951309_1996-06-23
1996-06-23
Cache hit for 50.0874654_14.4212535_1996-06-23
1996-06-26
result is back for  (-0.1277653, 51.5074456, datetime.date(1996, 6, 26))
1996-06-26
Cache hit for 48.8534951_2.3483915_1996-06-26
1996-06-30
Cache hit for 50.0874654_14.4212535_1996-06-30
1998-06-10
Cache hit for 34.0218454_-6.8408929_1998-06-10
1998-06-10
Cache hit for -15.7939869_-47.8828_1998-06-10
1998-06-11
Cache hit for 3.8689867_11.5213344_1998-06-11
1998-06-11
Cache hit for 41.8933203_12.4829321_1998-06-11
1998-06-12
Cache hit for -25.2800459_-57.6343814_1998-06-12
1998-06-12
Cache hit for 24.638916_46.7160104_1998-06-12
1998-06-13
Cache hit for 40.416782_-3.703507_1998-06-13
1998-06-13
Cache hit for 37.5666791_126.9782914_1998-06-13
1998-06-13
Cache hit for 52.3730796_4.8924534_1998-06-13
1998-06-15
Cache hit for 44.4361414_26.102684_1998-06-15
1998-06-15
result is back for  (-0.1277653, 51.5074456, datetime.date(1998, 6, 15))
1998-06-16
Cache hit for -15.7939869_-47.8828_1998-06-16
1998-06-16
Cache hit for 55.9533456_-3.1883749_1998-06-16
1998-06-17
Cache hit for -33.4376995_-70.6510671_1998-06-17
1998-06-17
Cache hit for 41.8933203_12.4829321_1998-06-17
1998-06-18
Cache hit for 48.8534951_2.3483915_1998-06-18
1998-06-19
Cache hit for 9.0643305_7.4892974_1998-06-19
1998-06-19
Cache hit for 40.416782_-3.703507_1998-06-19
1998-06-20
Cache hit for 50.8467372_4.352493_1998-06-20
1998-06-20
Cache hit for 52.3730796_4.8924534_1998-06-20
1998-06-22
Cache hit for 4.6533817_-74.0836331_1998-06-22
1998-06-22
result is back for  (26.102684, 44.4361414, datetime.date(1998, 6, 22))
1998-06-23
Cache hit for 41.8933203_12.4829321_1998-06-23
1998-06-23
Cache hit for -33.4376995_-70.6510671_1998-06-23
1998-06-23
Cache hit for 55.9533456_-3.1883749_1998-06-23
1998-06-23
Cache hit for -15.7939869_-47.8828_1998-06-23
1998-06-24
Cache hit for 9.0643305_7.4892974_1998-06-24
1998-06-24
Cache hit for -25.7459277_28.1879101_1998-06-24
1998-06-24
Cache hit for 40.416782_-3.703507_1998-06-24
1998-06-24
Cache hit for 48.8534951_2.3483915_1998-06-24
1998-06-25
Cache hit for 52.5173885_13.3951309_1998-06-25
1998-06-25
Cache hit for 52.3730796_4.8924534_1998-06-25
1998-06-25
Cache hit for 50.8467372_4.352493_1998-06-25
1998-06-26
Cache hit for 35.6768601_139.7638947_1998-06-26
1998-06-26
Cache hit for -34.6095579_-58.3887904_1998-06-26
1998-06-26
result is back for  (-74.0836331, 4.6533817, datetime.date(1998, 6, 26))
1998-06-26
Cache hit for 44.4361414_26.102684_1998-06-26
1998-06-27
Cache hit for 41.8933203_12.4829321_1998-06-27
1998-06-27
Cache hit for -15.7939869_-47.8828_1998-06-27
1998-06-28
Cache hit for 9.0643305_7.4892974_1998-06-28
1998-06-28
Cache hit for 48.8534951_2.3483915_1998-06-28
1998-06-29
Cache hit for 52.5173885_13.3951309_1998-06-29
1998-06-30
Cache hit for 44.4361414_26.102684_1998-06-30
1998-06-30
result is back for  (-58.3887904, -34.6095579, datetime.date(1998, 6, 30))
1998-07-03
Cache hit for 48.8534951_2.3483915_1998-07-03
1998-07-03
Cache hit for -15.7939869_-47.8828_1998-07-03
1998-07-04
Cache hit for 52.5173885_13.3951309_1998-07-04
1998-07-04
Cache hit for 52.3730796_4.8924534_1998-07-04
1998-07-07
Cache hit for -15.7939869_-47.8828_1998-07-07
1998-07-08
Cache hit for 48.8534951_2.3483915_1998-07-08
1998-07-11
Cache hit for 52.3730796_4.8924534_1998-07-11
1998-07-12
Cache hit for 48.8534951_2.3483915_1998-07-12
2000-06-19
Cache hit for 41.8933203_12.4829321_2000-06-19
2000-06-19
Cache hit for 50.8467372_4.352493_2000-06-19
2000-06-20
result is back for  (-0.1277653, 51.5074456, datetime.date(2000, 6, 20))
2000-06-20
Cache hit for 38.7077507_-9.1365919_2000-06-20
2000-06-21
Cache hit for 46.0500268_14.5069289_2000-06-21
2000-06-21
Cache hit for 52.3730796_4.8924534_2000-06-21
2000-06-21
Cache hit for 55.6867243_12.5700724_2000-06-21
2000-06-24
Cache hit for 39.9207759_32.8540497_2000-06-24
2000-06-24
Cache hit for 41.8933203_12.4829321_2000-06-24
2000-06-25
Cache hit for 40.416782_-3.703507_2000-06-25
2000-06-28
Cache hit for 48.8534951_2.3483915_2000-06-28
2000-06-29
Cache hit for 52.3730796_4.8924534_2000-06-29
2000-07-02
Cache hit for 48.8534951_2.3483915_2000-07-02
2002-06-01
Cache hit for -34.9058916_-56.1913095_2002-06-01
2002-06-01
Cache hit for 52.5173885_13.3951309_2002-06-01
2002-06-02
Cache hit for -34.6095579_-58.3887904_2002-06-02
2002-06-02
Cache hit for 40.416782_-3.703507_2002-06-02
2002-06-02
Cache hit for -25.2800459_-57.6343814_2002-06-02
2002-06-02
result is back for  (-0.1277653, 51.5074456, datetime.date(2002, 6, 2))
2002-06-03
Cache hit for -15.7939869_-47.8828_2002-06-03
2002-06-04
Cache hit for 35.6768601_139.7638947_2002-06-04
2002-06-06
Cache hit for 48.8534951_2.3483915_2002-06-06
2002-06-06
Cache hit for 3.8689867_11.5213344_2002-06-06
2002-06-07
result is back for  (-58.3887904, -34.6095579, datetime.date(2002, 6, 7))
2002-06-07
Cache hit for 59.3251172_18.0710935_2002-06-07
2002-06-07
Cache hit for 40.416782_-3.703507_2002-06-07
2002-06-08
Cache hit for -25.7459277_28.1879101_2002-06-08
2002-06-09
Cache hit for 9.9327707_-84.0796144_2002-06-09
2002-06-10
Cache hit for 36.8002068_10.1857757_2002-06-10
2002-06-11
Cache hit for 55.6867243_12.5700724_2002-06-11
2002-06-11
Cache hit for 3.8689867_11.5213344_2002-06-11
2002-06-11
Cache hit for 24.638916_46.7160104_2002-06-11
2002-06-11
Cache hit for 14.693425_-17.447938_2002-06-11
2002-06-12
Cache hit for -25.7459277_28.1879101_2002-06-12
2002-06-12
Cache hit for 46.0500268_14.5069289_2002-06-12
2002-06-12
Cache hit for 59.3251172_18.0710935_2002-06-12
2002-06-12
result is back for  (7.4892974, 9.0643305, datetime.date(2002, 6, 12))
2002-06-13
Cache hit for 9.9327707_-84.0796144_2002-06-13
2002-06-13
Cache hit for 39.9207759_32.8540497_2002-06-13
2002-06-13
Cache hit for -0.2201641_-78.5123274_2002-06-13
2002-06-13
Cache hit for 19.3207722_-99.1514678_2002-06-13
2002-06-14
Cache hit for 37.5666791_126.9782914_2002-06-14
2002-06-14
Cache hit for 50.8467372_4.352493_2002-06-14
2002-06-14
Cache hit for 35.6768601_139.7638947_2002-06-14
2002-06-15
result is back for  (12.5700724, 55.6867243, datetime.date(2002, 6, 15))
2002-06-15
Cache hit for 52.5173885_13.3951309_2002-06-15
2002-06-16
Cache hit for 40.416782_-3.703507_2002-06-16
2002-06-16
Cache hit for 59.3251172_18.0710935_2002-06-16
2002-06-17
Cache hit for -15.7939869_-47.8828_2002-06-17
2002-06-18
Cache hit for 35.6768601_139.7638947_2002-06-18
2002-06-18
Cache hit for 37.5666791_126.9782914_2002-06-18
2002-06-21
result is back for  (-0.1277653, 51.5074456, datetime.date(2002, 6, 21))
2002-06-22
Cache hit for 37.5666791_126.9782914_2002-06-22
2002-06-22
Cache hit for 14.693425_-17.447938_2002-06-22
2002-06-25
Cache hit for 37.5666791_126.9782914_2002-06-25
2002-06-26
Cache hit for -15.7939869_-47.8828_2002-06-26
2002-06-29
Cache hit for 37.5666791_126.9782914_2002-06-29
2002-06-30
Cache hit for 52.5173885_13.3951309_2002-06-30
2004-06-20
Cache hit for 38.7077507_-9.1365919_2004-06-20
2004-06-20
Cache hit for 55.625578_37.6063916_2004-06-20
2004-06-21
result is back for  (15.9772795, 45.8130967, datetime.date(2004, 6, 21))
2004-06-21
Cache hit for 46.9484742_7.4521749_2004-06-21
2004-06-22
Cache hit for 41.8933203_12.4829321_2004-06-22
2004-06-22
Cache hit for 55.6867243_12.5700724_2004-06-22
2004-06-23
Cache hit for 52.5173885_13.3951309_2004-06-23
2004-06-23
Cache hit for 52.3730796_4.8924534_2004-06-23
2004-06-24
result is back for  (-9.1365919, 38.7077507, datetime.date(2004, 6, 24))
2004-06-25
Cache hit for 48.8534951_2.3483915_2004-06-25
2004-06-26
Cache hit for 59.3251172_18.0710935_2004-06-26
2004-06-27
Cache hit for 50.0874654_14.4212535_2004-06-27
2004-06-30
Cache hit for 38.7077507_-9.1365919_2004-06-30
2004-07-01
Cache hit for 37.9755648_23.7348324_2004-07-01
2004-07-04
Cache hit for 38.7077507_-9.1365919_2004-07-04
2006-06-20
Cache hit for 52.5173885_13.3951309_2006-06-20
2006-06-20
result is back for  (18.0710935, 59.3251172, datetime.date(2006, 6, 20))
2006-06-20
Cache hit for 9.9327707_-84.0796144_2006-06-20
2006-06-20
Cache hit for -25.2800459_-57.6343814_2006-06-20
2006-06-21
Cache hit for 38.7077507_-9.1365919_2006-06-21
2006-06-21
Cache hit for 35.6892523_51.3896004_2006-06-21
2006-06-21
Cache hit for 52.3730796_4.8924534_2006-06-21
2006-06-22
Cache hit for 45.8130967_15.9772795_2006-06-22
2006-06-22
Cache hit for 35.6768601_139.7638947_2006-06-22
2006-06-22
Cache hit for 50.0874654_14.4212535_2006-06-22
2006-06-23
Cache hit for 50.4500336_30.5241361_2006-06-23
2006-06-23
Cache hit for 24.638916_46.7160104_2006-06-23
2006-06-23
Cache hit for 6.130419_1.215829_2006-06-23
2006-06-23
Cache hit for 46.9484742_7.4521749_2006-06-23
2006-06-24
Cache hit for -34.6095579_-58.3887904_2006-06-24
2006-06-24
Cache hit for 52.5173885_13.3951309_2006-06-24
2006-06-25
result is back for  (-0.1277653, 51.5074456, datetime.date(2006, 6, 25))
2006-06-25
Cache hit for 38.7077507_-9.1365919_2006-06-25
2006-06-26
Cache hit for 41.8933203_12.4829321_2006-06-26
2006-06-26
Cache hit for 46.9484742_7.4521749_2006-06-26
2006-06-27
Cache hit for -15.7939869_-47.8828_2006-06-27
2006-06-27
Cache hit for 40.416782_-3.703507_2006-06-27
2006-06-30
Cache hit for 52.5173885_13.3951309_2006-06-30
2006-06-30
Cache hit for 41.8933203_12.4829321_2006-06-30
2006-07-01
Cache hit for -15.7939869_-47.8828_2006-07-01
2006-07-01
result is back for  (-0.1277653, 51.5074456, datetime.date(2006, 7, 1))
2006-07-04
Cache hit for 52.5173885_13.3951309_2006-07-04
2006-07-05
Cache hit for 38.7077507_-9.1365919_2006-07-05
2006-07-08
Cache hit for 52.5173885_13.3951309_2006-07-08
2006-07-09
Cache hit for 41.8933203_12.4829321_2006-07-09
2008-06-15
Cache hit for 39.9207759_32.8540497_2008-06-15
2008-06-15
Cache hit for 46.9484742_7.4521749_2008-06-15
2008-06-16
Cache hit for 52.2319581_21.0067249_2008-06-16
2008-06-16
Cache hit for 48.2083537_16.3725042_2008-06-16
2008-06-17
Cache hit for 48.8534951_2.3483915_2008-06-17
2008-06-17
Cache hit for 52.3730796_4.8924534_2008-06-17
2008-06-18
Cache hit for 37.9755648_23.7348324_2008-06-18
2008-06-18
Cache hit for 55.625578_37.6063916_2008-06-18
2008-06-19
Cache hit for 38.7077507_-9.1365919_2008-06-19
2008-06-20
Cache hit for 45.8130967_15.9772795_2008-06-20
2008-06-21
Cache hit for 52.3730796_4.8924534_2008-06-21
2008-06-22
Cache hit for 40.416782_-3.703507_2008-06-22
2008-06-25
Cache hit for 52.5173885_13.3951309_2008-06-25
2008-06-26
Cache hit for 55.625578_37.6063916_2008-06-26
2008-06-29
Cache hit for 52.5173885_13.3951309_2008-06-29
2010-06-22
Cache hit for 9.0643305_7.4892974_2010-06-22
2010-06-22
Cache hit for 19.3207722_-99.1514678_2010-06-22
2010-06-22
Cache hit for 37.9755648_23.7348324_2010-06-22
2010-06-22
Cache hit for -25.7459277_28.1879101_2010-06-22
2010-06-23
Cache hit for 5.5571096_-0.2012376_2010-06-23
2010-06-23
Cache hit for -35.2975906_149.1012676_2010-06-23
2010-06-23
result is back for  (14.5069289, 46.0500268, datetime.date(2010, 6, 23))
2010-06-24
Cache hit for 48.1516988_17.1093063_2010-06-24
2010-06-24
Cache hit for 55.6867243_12.5700724_2010-06-24
2010-06-24
Cache hit for 3.8689867_11.5213344_2010-06-24
2010-06-24
Cache hit for -25.2800459_-57.6343814_2010-06-24
2010-06-25
Cache hit for 38.7077507_-9.1365919_2010-06-25
2010-06-25
Cache hit for 46.9484742_7.4521749_2010-06-25
2010-06-25
Cache hit for 39.0167979_125.7473609_2010-06-25
2010-06-25
Cache hit for -33.4376995_-70.6510671_2010-06-25
2010-06-26
Cache hit for -34.9058916_-56.1913095_2010-06-26
2010-06-27
result is back for  (13.3951309, 52.5173885, datetime.date(2010, 6, 27))
2010-06-27
Cache hit for -34.6095579_-58.3887904_2010-06-27
2010-06-28
Cache hit for -15.7939869_-47.8828_2010-06-28
2010-06-28
Cache hit for 52.3730796_4.8924534_2010-06-28
2010-06-29
Cache hit for -25.2800459_-57.6343814_2010-06-29
2010-06-29
Cache hit for 40.416782_-3.703507_2010-06-29
2010-07-02
Cache hit for -34.9058916_-56.1913095_2010-07-02
2010-07-02
Cache hit for 52.3730796_4.8924534_2010-07-02
2010-07-03
Cache hit for -34.6095579_-58.3887904_2010-07-03
2010-07-03
Cache hit for -25.2800459_-57.6343814_2010-07-03
2010-07-06
Cache hit for -34.9058916_-56.1913095_2010-07-06
2010-07-07
Cache hit for 52.5173885_13.3951309_2010-07-07
2010-07-10
Cache hit for -34.9058916_-56.1913095_2010-07-10
2010-07-11
Cache hit for 52.3730796_4.8924534_2010-07-11
2012-06-16
Cache hit for 37.9755648_23.7348324_2012-06-16
2012-06-16
Cache hit for 52.2319581_21.0067249_2012-06-16
2012-06-17
Cache hit for 55.6867243_12.5700724_2012-06-17
2012-06-17
Cache hit for 38.7077507_-9.1365919_2012-06-17
2012-06-18
Cache hit for 41.8933203_12.4829321_2012-06-18
2012-06-18
Cache hit for 45.8130967_15.9772795_2012-06-18
2012-06-19
result is back for  (30.5241361, 50.4500336, datetime.date(2012, 6, 19))
2012-06-19
Cache hit for 59.3251172_18.0710935_2012-06-19
2012-06-21
Cache hit for 50.0874654_14.4212535_2012-06-21
2012-06-22
Cache hit for 52.5173885_13.3951309_2012-06-22
2012-06-23
Cache hit for 40.416782_-3.703507_2012-06-23
2012-06-24
result is back for  (-0.1277653, 51.5074456, datetime.date(2012, 6, 24))
2012-06-27
Cache hit for 38.7077507_-9.1365919_2012-06-27
2012-06-28
Cache hit for 52.5173885_13.3951309_2012-06-28
2012-07-01
Cache hit for 40.416782_-3.703507_2012-07-01
2014-06-23
result is back for  (-47.8828, -15.7939869, datetime.date(2014, 6, 23))
2014-06-23
result is back for  (4.8924534, 52.3730796, datetime.date(2014, 6, 23))
2014-06-23
result is back for  (15.9772795, 45.8130967, datetime.date(2014, 6, 23))
2014-06-23
result is back for  (149.1012676, -35.2975906, datetime.date(2014, 6, 23))
2014-06-24
result is back for  (12.4829321, 41.8933203, datetime.date(2014, 6, 24))
2014-06-24
result is back for  (139.7638947, 35.6768601, datetime.date(2014, 6, 24))
2014-06-24
result is back for  (-84.0796144, 9.9327707, datetime.date(2014, 6, 24))
2014-06-24
result is back for  (23.7348324, 37.9755648, datetime.date(2014, 6, 24))
2014-06-25
result is back for  (18.4126147, 43.8570713, datetime.date(2014, 6, 25))
2014-06-25
result is back for  (-87.2047053, 14.1058135, datetime.date(2014, 6, 25))
2014-06-25
result is back for  (7.4892974, 9.0643305, datetime.date(2014, 6, 25))
2014-06-25
result is back for  (-78.5123274, -0.2201641, datetime.date(2014, 6, 25))
2014-06-26
result is back for  (-9.1365919, 38.7077507, datetime.date(2014, 6, 26))
2014-06-26
result is back for  (126.9782914, 37.5666791, datetime.date(2014, 6, 26))
2014-06-26
result is back for  (3.0588445, 36.7729333, datetime.date(2014, 6, 26))
2014-06-28
result is back for  (-74.0836331, 4.6533817, datetime.date(2014, 6, 28))
2014-06-28
result is back for  (-47.8828, -15.7939869, datetime.date(2014, 6, 28))
2014-06-29
result is back for  (-84.0796144, 9.9327707, datetime.date(2014, 6, 29))
2014-06-29
result is back for  (4.8924534, 52.3730796, datetime.date(2014, 6, 29))
2014-06-30
result is back for  (13.3951309, 52.5173885, datetime.date(2014, 6, 30))
2014-06-30
result is back for  (2.3483915, 48.8534951, datetime.date(2014, 6, 30))
2014-07-01
result is back for  (-58.3887904, -34.6095579, datetime.date(2014, 7, 1))
2014-07-04
result is back for  (2.3483915, 48.8534951, datetime.date(2014, 7, 4))
2014-07-04
result is back for  (-47.8828, -15.7939869, datetime.date(2014, 7, 4))
2014-07-05
result is back for  (-58.3887904, -34.6095579, datetime.date(2014, 7, 5))
2014-07-05
result is back for  (4.8924534, 52.3730796, datetime.date(2014, 7, 5))
2014-07-08
result is back for  (-47.8828, -15.7939869, datetime.date(2014, 7, 8))
2014-07-09
result is back for  (4.8924534, 52.3730796, datetime.date(2014, 7, 9))
2014-07-12
result is back for  (-47.8828, -15.7939869, datetime.date(2014, 7, 12))
2014-07-13
result is back for  (13.3951309, 52.5173885, datetime.date(2014, 7, 13))
2016-06-19
result is back for  (26.102684, 44.4361414, datetime.date(2016, 6, 19))
2016-06-19
result is back for  (2.3483915, 48.8534951, datetime.date(2016, 6, 19))
2016-06-20
result is back for  (17.1093063, 48.1516988, datetime.date(2016, 6, 20))
2016-06-20
result is back for  (37.6063916, 55.625578, datetime.date(2016, 6, 20))
2016-06-21
result is back for  (-5.9301829, 54.596391, datetime.date(2016, 6, 21))
2016-06-21
result is back for  (30.5241361, 50.4500336, datetime.date(2016, 6, 21))
2016-06-21
result is back for  (15.9772795, 45.8130967, datetime.date(2016, 6, 21))
2016-06-21
result is back for  (14.4212535, 50.0874654, datetime.date(2016, 6, 21))
2016-06-22
result is back for  (12.4829321, 41.8933203, datetime.date(2016, 6, 22))
2016-06-22
result is back for  (19.1457723, 47.4813896, datetime.date(2016, 6, 22))
2016-06-22
result is back for  (-21.9422367, 64.145981, datetime.date(2016, 6, 22))
2016-06-22
result is back for  (18.0710935, 59.3251172, datetime.date(2016, 6, 22))
2016-06-25
result is back for  (-3.1791934, 51.4816546, datetime.date(2016, 6, 25))
2016-06-25

In [255]:

unique = result[['away_lat', 'away_lon', 'date']].drop_duplicates()

unique['weather'] = unique.apply(
    lambda row: get_weather(row['away_lat'], row['away_lon'], row['date']),
    axis=1
)

weather_df = unique['weather'].apply(pd.Series).add_prefix("away_")
unique = pd.concat([unique, weather_df], axis=1).drop(columns='weather')

result = result.merge(unique, on=['away_lat', 'away_lon', 'date'], how='left')

1994-06-18
result is back for  (-6.2605593, 53.3493795, datetime.date(1994, 6, 18))
1994-06-19
result is back for  (-6.8408929, 34.0218454, datetime.date(1994, 6, 19))
1994-06-21
result is back for  (23.7348324, 37.9755648, datetime.date(1994, 6, 21))
1994-06-21
result is back for  (-3.703507, 40.416782, datetime.date(1994, 6, 21))
1994-06-22
result is back for  (7.4521749, 46.9484742, datetime.date(1994, 6, 22))
1994-06-24
result is back for  (11.5213344, 3.8689867, datetime.date(1994, 6, 24))
1994-06-24
result is back for  (-6.2605593, 53.3493795, datetime.date(1994, 6, 24))
1994-06-25
result is back for  (4.8924534, 52.3730796, datetime.date(1994, 6, 25))
1994-06-26
result is back for  (23.7348324, 37.9755648, datetime.date(1994, 6, 26))
1994-06-26
result is back for  (-74.0836331, 4.6533817, datetime.date(1994, 6, 26))
1994-06-27
result is back for  (-3.703507, 40.416782, datetime.date(1994, 6, 27))
1994-06-27
result is back for  (126.9782914, 37.5666791, datetime.date(1994, 6, 27))
1994-06-28
result is back for  (11.5213344, 3.8689867, datetime.date(1994, 6, 28))
1994-06-28
result is back for  (-99.1514678, 19.3207722, datetime.date(1994, 6, 28))
1994-06-28
result is back for  (10.7389701, 59.9133301, datetime.date(1994, 6, 28))
1994-06-28
result is back for  (18.0710935, 59.3251172, datetime.date(1994, 6, 28))
1994-06-29
result is back for  (4.8924534, 52.3730796, datetime.date(1994, 6, 29))
1994-06-29
result is back for  (46.7160104, 24.638916, datetime.date(1994, 6, 29))
1994-07-02
result is back for  (4.352493, 50.8467372, datetime.date(1994, 7, 2))
1994-07-02
result is back for  (7.4521749, 46.9484742, datetime.date(1994, 7, 2))
1994-07-03
result is back for  (-58.3887904, -34.6095579, datetime.date(1994, 7, 3))
1994-07-03
result is back for  (18.0710935, 59.3251172, datetime.date(1994, 7, 3))
1994-07-04
result is back for  (-6.2605593, 53.3493795, datetime.date(1994, 7, 4))
1994-07-05
result is back for  (12.4829321, 41.8933203, datetime.date(1994, 7, 5))
1994-07-05
result is back for  (23.3217359, 42.6977028, datetime.date(1994, 7, 5))
1994-07-09
result is back for  (-3.703507, 40.416782, datetime.date(1994, 7, 9))
1994-07-09
result is back for  (-47.8828, -15.7939869, datetime.date(1994, 7, 9))
1994-07-10
result is back for  (13.3951309, 52.5173885, datetime.date(1994, 7, 10))
1994-07-10
result is back for  (18.0710935, 59.3251172, datetime.date(1994, 7, 10))
1994-07-13
result is back for  (12.4829321, 41.8933203, datetime.date(1994, 7, 13))
1994-07-16
result is back for  (23.3217359, 42.6977028, datetime.date(1994, 7, 16))
1994-07-17
result is back for  (12.4829321, 41.8933203, datetime.date(1994, 7, 17))
1996-06-08
result is back for  (7.4521749, 46.9484742, datetime.date(1996, 6, 8))
1996-06-09
result is back for  (-9.1365919, 38.7077507, datetime.date(1996, 6, 9))
1996-06-09
result is back for  (23.3217359, 42.6977028, datetime.date(1996, 6, 9))
1996-06-10
result is back for  (2.3483915, 48.8534951, datetime.date(1996, 6, 10))
1996-06-10
result is back for  (-3.1883749, 55.9533456, datetime.date(1996, 6, 10))
1996-06-11
result is back for  (37.6063916, 55.625578, datetime.date(1996, 6, 11))
1996-06-13
result is back for  (4.8924534, 52.3730796, datetime.date(1996, 6, 13))
1996-06-13
result is back for  (26.102684, 44.4361414, datetime.date(1996, 6, 13))
1996-06-15
result is back for  (-3.703507, 40.416782, datetime.date(1996, 6, 15))
1996-06-15
result is back for  (-3.1883749, 55.9533456, datetime.date(1996, 6, 15))
1996-06-16
result is back for  (13.3951309, 52.5173885, datetime.date(1996, 6, 16))
1996-06-18
result is back for  (23.3217359, 42.6977028, datetime.date(1996, 6, 18))
1996-06-18
result is back for  (4.8924534, 52.3730796, datetime.date(1996, 6, 18))
1996-06-18
result is back for  (-3.703507, 40.416782, datetime.date(1996, 6, 18))
1996-06-18
result is back for  (7.4521749, 46.9484742, datetime.date(1996, 6, 18))
1996-06-19
result is back for  (-9.1365919, 38.7077507, datetime.date(1996, 6, 19))
1996-06-19
result is back for  (13.3951309, 52.5173885, datetime.date(1996, 6, 19))
1996-06-19
result is back for  (14.4212535, 50.0874654, datetime.date(1996, 6, 19))
1996-06-19
result is back for  (12.5700724, 55.6867243, datetime.date(1996, 6, 19))
1996-06-22
result is back for  (4.8924534, 52.3730796, datetime.date(1996, 6, 22))
1996-06-22
result is back for  (-3.703507, 40.416782, datetime.date(1996, 6, 22))
1996-06-23
result is back for  (15.9772795, 45.8130967, datetime.date(1996, 6, 23))
1996-06-23
result is back for  (-9.1365919, 38.7077507, datetime.date(1996, 6, 23))
1996-06-26
result is back for  (13.3951309, 52.5173885, datetime.date(1996, 6, 26))
1996-06-26
result is back for  (14.4212535, 50.0874654, datetime.date(1996, 6, 26))
1996-06-30
result is back for  (13.3951309, 52.5173885, datetime.date(1996, 6, 30))
1998-06-10
result is back for  (10.7389701, 59.9133301, datetime.date(1998, 6, 10))
1998-06-10
result is back for  (-3.1883749, 55.9533456, datetime.date(1998, 6, 10))
1998-06-11
result is back for  (16.3725042, 48.2083537, datetime.date(1998, 6, 11))
1998-06-11
result is back for  (-70.6510671, -33.4376995, datetime.date(1998, 6, 11))
1998-06-12
result is back for  (23.3217359, 42.6977028, datetime.date(1998, 6, 12))
1998-06-12
result is back for  (12.5700724, 55.6867243, datetime.date(1998, 6, 12))
1998-06-13
result is back for  (7.4892974, 9.0643305, datetime.date(1998, 6, 13))
1998-06-13
result is back for  (-99.1514678, 19.3207722, datetime.date(1998, 6, 13))
1998-06-13
result is back for  (4.352493, 50.8467372, datetime.date(1998, 6, 13))
1998-06-15
result is back for  (-74.0836331, 4.6533817, datetime.date(1998, 6, 15))
1998-06-15
result is back for  (10.1857757, 36.8002068, datetime.date(1998, 6, 15))
1998-06-16
result is back for  (-6.8408929, 34.0218454, datetime.date(1998, 6, 16))
1998-06-16
result is back for  (10.7389701, 59.9133301, datetime.date(1998, 6, 16))
1998-06-17
result is back for  (16.3725042, 48.2083537, datetime.date(1998, 6, 17))
1998-06-17
result is back for  (11.5213344, 3.8689867, datetime.date(1998, 6, 17))
1998-06-18
result is back for  (46.7160104, 24.638916, datetime.date(1998, 6, 18))
1998-06-19
result is back for  (23.3217359, 42.6977028, datetime.date(1998, 6, 19))
1998-06-19
result is back for  (-57.6343814, -25.2800459, datetime.date(1998, 6, 19))
1998-06-20
result is back for  (-99.1514678, 19.3207722, datetime.date(1998, 6, 20))
1998-06-20
result is back for  (126.9782914, 37.5666791, datetime.date(1998, 6, 20))
1998-06-22
result is back for  (10.1857757, 36.8002068, datetime.date(1998, 6, 22))
1998-06-22
result is back for  (-0.1277653, 51.5074456, datetime.date(1998, 6, 22))
1998-06-23
result is back for  (16.3725042, 48.2083537, datetime.date(1998, 6, 23))
1998-06-23
result is back for  (11.5213344, 3.8689867, datetime.date(1998, 6, 23))
1998-06-23
result is back for  (-6.8408929, 34.0218454, datetime.date(1998, 6, 23))
1998-06-23
result is back for  (10.7389701, 59.9133301, datetime.date(1998, 6, 23))
1998-06-24
result is back for  (-57.6343814, -25.2800459, datetime.date(1998, 6, 24))
1998-06-24
result is back for  (46.7160104, 24.638916, datetime.date(1998, 6, 24))
1998-06-24
result is back for  (23.3217359, 42.6977028, datetime.date(1998, 6, 24))
1998-06-24
result is back for  (12.5700724, 55.6867243, datetime.date(1998, 6, 24))
1998-06-25
result is back for  (51.3896004, 35.6892523, datetime.date(1998, 6, 25))
1998-06-25
result is back for  (-99.1514678, 19.3207722, datetime.date(1998, 6, 25))
1998-06-25
result is back for  (126.9782914, 37.5666791, datetime.date(1998, 6, 25))
1998-06-26
result is back for  (-76.7928128, 17.9712148, datetime.date(1998, 6, 26))
1998-06-26
result is back for  (15.9772795, 45.8130967, datetime.date(1998, 6, 26))
1998-06-26
result is back for  (-0.1277653, 51.5074456, datetime.date(1998, 6, 26))
1998-06-26
result is back for  (10.1857757, 36.8002068, datetime.date(1998, 6, 26))
1998-06-27
result is back for  (10.7389701, 59.9133301, datetime.date(1998, 6, 27))
1998-06-27
result is back for  (-70.6510671, -33.4376995, datetime.date(1998, 6, 27))
1998-06-28
result is back for  (12.5700724, 55.6867243, datetime.date(1998, 6, 28))
1998-06-28
result is back for  (-57.6343814, -25.2800459, datetime.date(1998, 6, 28))
1998-06-29
result is back for  (-99.1514678, 19.3207722, datetime.date(1998, 6, 29))
1998-06-30
result is back for  (15.9772795, 45.8130967, datetime.date(1998, 6, 30))
1998-06-30
result is back for  (-0.1277653, 51.5074456, datetime.date(1998, 6, 30))
1998-07-03
result is back for  (12.4829321, 41.8933203, datetime.date(1998, 7, 3))
1998-07-03
result is back for  (12.5700724, 55.6867243, datetime.date(1998, 7, 3))
1998-07-04
result is back for  (15.9772795, 45.8130967, datetime.date(1998, 7, 4))
1998-07-04
result is back for  (-58.3887904, -34.6095579, datetime.date(1998, 7, 4))
1998-07-07
result is back for  (4.8924534, 52.3730796, datetime.date(1998, 7, 7))
1998-07-08
result is back for  (15.9772795, 45.8130967, datetime.date(1998, 7, 8))
1998-07-11
result is back for  (15.9772795, 45.8130967, datetime.date(1998, 7, 11))
1998-07-12
result is back for  (-47.8828, -15.7939869, datetime.date(1998, 7, 12))
2000-06-19
result is back for  (18.0710935, 59.3251172, datetime.date(2000, 6, 19))
2000-06-19
result is back for  (32.8540497, 39.9207759, datetime.date(2000, 6, 19))
2000-06-20
result is back for  (26.102684, 44.4361414, datetime.date(2000, 6, 20))
2000-06-20
result is back for  (13.3951309, 52.5173885, datetime.date(2000, 6, 20))
2000-06-21
result is back for  (10.7389701, 59.9133301, datetime.date(2000, 6, 21))
2000-06-21
result is back for  (2.3483915, 48.8534951, datetime.date(2000, 6, 21))
2000-06-21
result is back for  (14.4212535, 50.0874654, datetime.date(2000, 6, 21))
2000-06-24
result is back for  (-9.1365919, 38.7077507, datetime.date(2000, 6, 24))
2000-06-24
result is back for  (26.102684, 44.4361414, datetime.date(2000, 6, 24))
2000-06-25
result is back for  (2.3483915, 48.8534951, datetime.date(2000, 6, 25))
2000-06-28
result is back for  (-9.1365919, 38.7077507, datetime.date(2000, 6, 28))
2000-06-29
result is back for  (12.4829321, 41.8933203, datetime.date(2000, 6, 29))
2000-07-02
result is back for  (12.4829321, 41.8933203, datetime.date(2000, 7, 2))
2002-06-01
result is back for  (12.5700724, 55.6867243, datetime.date(2002, 6, 1))
2002-06-01
result is back for  (46.7160104, 24.638916, datetime.date(2002, 6, 1))
2002-06-02
result is back for  (7.4892974, 9.0643305, datetime.date(2002, 6, 2))
2002-06-02
result is back for  (14.5069289, 46.0500268, datetime.date(2002, 6, 2))
2002-06-02
result is back for  (28.1879101, -25.7459277, datetime.date(2002, 6, 2))
2002-06-02
result is back for  (18.0710935, 59.3251172, datetime.date(2002, 6, 2))
2002-06-03
result is back for  (32.8540497, 39.9207759, datetime.date(2002, 6, 3))
2002-06-04
result is back for  (4.352493, 50.8467372, datetime.date(2002, 6, 4))
2002-06-06
result is back for  (-56.1913095, -34.9058916, datetime.date(2002, 6, 6))
2002-06-06
result is back for  (46.7160104, 24.638916, datetime.date(2002, 6, 6))
2002-06-07
result is back for  (-0.1277653, 51.5074456, datetime.date(2002, 6, 7))
2002-06-07
result is back for  (7.4892974, 9.0643305, datetime.date(2002, 6, 7))
2002-06-07
result is back for  (-57.6343814, -25.2800459, datetime.date(2002, 6, 7))
2002-06-08
result is back for  (14.5069289, 46.0500268, datetime.date(2002, 6, 8))
2002-06-09
result is back for  (32.8540497, 39.9207759, datetime.date(2002, 6, 9))
2002-06-10
result is back for  (4.352493, 50.8467372, datetime.date(2002, 6, 10))
2002-06-11
result is back for  (2.3483915, 48.8534951, datetime.date(2002, 6, 11))
2002-06-11
result is back for  (13.3951309, 52.5173885, datetime.date(2002, 6, 11))
2002-06-11
result is back for  (-6.2605593, 53.3493795, datetime.date(2002, 6, 11))
2002-06-11
result is back for  (-56.1913095, -34.9058916, datetime.date(2002, 6, 11))
2002-06-12
result is back for  (-3.703507, 40.416782, datetime.date(2002, 6, 12))
2002-06-12
result is back for  (-57.6343814, -25.2800459, datetime.date(2002, 6, 12))
2002-06-12
result is back for  (-58.3887904, -34.6095579, datetime.date(2002, 6, 12))
2002-06-12
result is back for  (-0.1277653, 51.5074456, datetime.date(2002, 6, 12))
2002-06-13
result is back for  (-47.8828, -15.7939869, datetime.date(2002, 6, 13))
2002-06-13
result is back for  (116.3912972, 39.9057136, datetime.date(2002, 6, 13))
2002-06-13
result is back for  (15.9772795, 45.8130967, datetime.date(2002, 6, 13))
2002-06-13
result is back for  (12.4829321, 41.8933203, datetime.date(2002, 6, 13))
2002-06-14
result is back for  (-9.1365919, 38.7077507, datetime.date(2002, 6, 14))
2002-06-14
result is back for  (37.6063916, 55.625578, datetime.date(2002, 6, 14))
2002-06-14
result is back for  (10.1857757, 36.8002068, datetime.date(2002, 6, 14))
2002-06-15
result is back for  (-0.1277653, 51.5074456, datetime.date(2002, 6, 15))
2002-06-15
result is back for  (-57.6343814, -25.2800459, datetime.date(2002, 6, 15))
2002-06-16
result is back for  (-6.2605593, 53.3493795, datetime.date(2002, 6, 16))
2002-06-16
result is back for  (-17.447938, 14.693425, datetime.date(2002, 6, 16))
2002-06-17
result is back for  (4.352493, 50.8467372, datetime.date(2002, 6, 17))
2002-06-18
result is back for  (32.8540497, 39.9207759, datetime.date(2002, 6, 18))
2002-06-18
result is back for  (12.4829321, 41.8933203, datetime.date(2002, 6, 18))
2002-06-21
result is back for  (-47.8828, -15.7939869, datetime.date(2002, 6, 21))
2002-06-22
result is back for  (-3.703507, 40.416782, datetime.date(2002, 6, 22))
2002-06-22
result is back for  (32.8540497, 39.9207759, datetime.date(2002, 6, 22))
2002-06-25
result is back for  (13.3951309, 52.5173885, datetime.date(2002, 6, 25))
2002-06-26
result is back for  (32.8540497, 39.9207759, datetime.date(2002, 6, 26))
2002-06-29
result is back for  (32.8540497, 39.9207759, datetime.date(2002, 6, 29))
2002-06-30
result is back for  (-47.8828, -15.7939869, datetime.date(2002, 6, 30))
2004-06-20
result is back for  (-3.703507, 40.416782, datetime.date(2004, 6, 20))
2004-06-20
result is back for  (23.7348324, 37.9755648, datetime.date(2004, 6, 20))
2004-06-21
result is back for  (-0.1277653, 51.5074456, datetime.date(2004, 6, 21))
2004-06-21
result is back for  (2.3483915, 48.8534951, datetime.date(2004, 6, 21))
2004-06-22
result is back for  (23.3217359, 42.6977028, datetime.date(2004, 6, 22))
2004-06-22
result is back for  (18.0710935, 59.3251172, datetime.date(2004, 6, 22))
2004-06-23
result is back for  (14.4212535, 50.0874654, datetime.date(2004, 6, 23))
2004-06-23
result is back for  (24.1051846, 56.9493977, datetime.date(2004, 6, 23))
2004-06-24
result is back for  (-0.1277653, 51.5074456, datetime.date(2004, 6, 24))
2004-06-25
result is back for  (23.7348324, 37.9755648, datetime.date(2004, 6, 25))
2004-06-26
result is back for  (4.8924534, 52.3730796, datetime.date(2004, 6, 26))
2004-06-27
result is back for  (12.5700724, 55.6867243, datetime.date(2004, 6, 27))
2004-06-30
result is back for  (4.8924534, 52.3730796, datetime.date(2004, 6, 30))
2004-07-01
result is back for  (14.4212535, 50.0874654, datetime.date(2004, 7, 1))
2004-07-04
result is back for  (23.7348324, 37.9755648, datetime.date(2004, 7, 4))
2006-06-20
result is back for  (-78.5123274, -0.2201641, datetime.date(2006, 6, 20))
2006-06-20
result is back for  (-0.1277653, 51.5074456, datetime.date(2006, 6, 20))
2006-06-20
result is back for  (21.0067249, 52.2319581, datetime.date(2006, 6, 20))
2006-06-20
result is back for  (-61.5180173, 10.6572678, datetime.date(2006, 6, 20))
2006-06-21
result is back for  (-99.1514678, 19.3207722, datetime.date(2006, 6, 21))
2006-06-21
result is back for  (13.2439512, -8.8272699, datetime.date(2006, 6, 21))
2006-06-21
result is back for  (-58.3887904, -34.6095579, datetime.date(2006, 6, 21))
2006-06-22
result is back for  (149.1012676, -35.2975906, datetime.date(2006, 6, 22))
2006-06-22
result is back for  (-47.8828, -15.7939869, datetime.date(2006, 6, 22))
2006-06-22
result is back for  (12.4829321, 41.8933203, datetime.date(2006, 6, 22))
2006-06-23
result is back for  (10.1857757, 36.8002068, datetime.date(2006, 6, 23))
2006-06-23
result is back for  (-3.703507, 40.416782, datetime.date(2006, 6, 23))
2006-06-23
result is back for  (2.3483915, 48.8534951, datetime.date(2006, 6, 23))
2006-06-23
result is back for  (126.9782914, 37.5666791, datetime.date(2006, 6, 23))
2006-06-24
result is back for  (-99.1514678, 19.3207722, datetime.date(2006, 6, 24))
2006-06-24
result is back for  (18.0710935, 59.3251172, datetime.date(2006, 6, 24))
2006-06-25
result is back for  (-78.5123274, -0.2201641, datetime.date(2006, 6, 25))
2006-06-25
result is back for  (4.8924534, 52.3730796, datetime.date(2006, 6, 25))
2006-06-26
result is back for  (149.1012676, -35.2975906, datetime.date(2006, 6, 26))
2006-06-26
result is back for  (30.5241361, 50.4500336, datetime.date(2006, 6, 26))
2006-06-27
result is back for  (-0.2012376, 5.5571096, datetime.date(2006, 6, 27))
2006-06-27
result is back for  (2.3483915, 48.8534951, datetime.date(2006, 6, 27))
2006-06-30
result is back for  (-58.3887904, -34.6095579, datetime.date(2006, 6, 30))
2006-06-30
result is back for  (30.5241361, 50.4500336, datetime.date(2006, 6, 30))
2006-07-01
result is back for  (2.3483915, 48.8534951, datetime.date(2006, 7, 1))
2006-07-01
result is back for  (-9.1365919, 38.7077507, datetime.date(2006, 7, 1))
2006-07-04
result is back for  (12.4829321, 41.8933203, datetime.date(2006, 7, 4))
2006-07-05
result is back for  (2.3483915, 48.8534951, datetime.date(2006, 7, 5))
2006-07-08
result is back for  (-9.1365919, 38.7077507, datetime.date(2006, 7, 8))
2006-07-09
result is back for  (2.3483915, 48.8534951, datetime.date(2006, 7, 9))
2008-06-15
result is back for  (14.4212535, 50.0874654, datetime.date(2008, 6, 15))
2008-06-15
result is back for  (-9.1365919, 38.7077507, datetime.date(2008, 6, 15))
2008-06-16
result is back for  (15.9772795, 45.8130967, datetime.date(2008, 6, 16))
2008-06-16
result is back for  (13.3951309, 52.5173885, datetime.date(2008, 6, 16))
2008-06-17
result is back for  (12.4829321, 41.8933203, datetime.date(2008, 6, 17))
2008-06-17
result is back for  (26.102684, 44.4361414, datetime.date(2008, 6, 17))
2008-06-18
result is back for  (-3.703507, 40.416782, datetime.date(2008, 6, 18))
2008-06-18
result is back for  (18.0710935, 59.3251172, datetime.date(2008, 6, 18))
2008-06-19
result is back for  (13.3951309, 52.5173885, datetime.date(2008, 6, 19))
2008-06-20
result is back for  (32.8540497, 39.9207759, datetime.date(2008, 6, 20))
2008-06-21
result is back for  (37.6063916, 55.625578, datetime.date(2008, 6, 21))
2008-06-22
result is back for  (12.4829321, 41.8933203, datetime.date(2008, 6, 22))
2008-06-25
result is back for  (32.8540497, 39.9207759, datetime.date(2008, 6, 25))
2008-06-26
result is back for  (-3.703507, 40.416782, datetime.date(2008, 6, 26))
2008-06-29
result is back for  (-3.703507, 40.416782, datetime.date(2008, 6, 29))
2010-06-22
result is back for  (126.9782914, 37.5666791, datetime.date(2010, 6, 22))
2010-06-22
result is back for  (-56.1913095, -34.9058916, datetime.date(2010, 6, 22))
2010-06-22
result is back for  (-58.3887904, -34.6095579, datetime.date(2010, 6, 22))
2010-06-22
result is back for  (2.3483915, 48.8534951, datetime.date(2010, 6, 22))
2010-06-23
result is back for  (13.3951309, 52.5173885, datetime.date(2010, 6, 23))
2010-06-23
result is back for  (20.4456588, 44.8153318, datetime.date(2010, 6, 23))
2010-06-23
result is back for  (-0.1277653, 51.5074456, datetime.date(2010, 6, 23))
2010-06-24
result is back for  (12.4829321, 41.8933203, datetime.date(2010, 6, 24))
2010-06-24
result is back for  (139.7638947, 35.6768601, datetime.date(2010, 6, 24))
2010-06-24
result is back for  (4.8924534, 52.3730796, datetime.date(2010, 6, 24))
2010-06-24

In [256]:

unique = result[['stadium_lat', 'stadium_lon', 'date']].drop_duplicates()

unique['weather'] = unique.apply(
    lambda row: get_weather(row['stadium_lat'], row['stadium_lon'], row['date']),
    axis=1
)

weather_df = unique['weather'].apply(pd.Series).add_prefix("stadium_")
unique = pd.concat([unique, weather_df], axis=1).drop(columns='weather')

result = result.merge(unique, on=['stadium_lat', 'stadium_lon', 'date'], how='left')

1994-06-18
result is back for  (-74.0970865, 40.833989, datetime.date(1994, 6, 18))
1994-06-19
result is back for  (-81.379045, 28.5421218, datetime.date(1994, 6, 19))
1994-06-21
result is back for  (-71.2478308, 42.0653768, datetime.date(1994, 6, 21))
1994-06-21
result is back for  (-87.6244212, 41.8755616, datetime.date(1994, 6, 21))
1994-06-22
result is back for  (-83.2910468, 42.6389216, datetime.date(1994, 6, 22))
1994-06-24
result is back for  (-122.1598465, 37.4443293, datetime.date(1994, 6, 24))
1994-06-24
result is back for  (-81.379045, 28.5421218, datetime.date(1994, 6, 24))
1994-06-25
result is back for  (-81.379045, 28.5421218, datetime.date(1994, 6, 25))
1994-06-26
result is back for  (-87.6244212, 41.8755616, datetime.date(1994, 6, 26))
1994-06-26
result is back for  (-122.1598465, 37.4443293, datetime.date(1994, 6, 26))
1994-06-27
result is back for  (-87.6244212, 41.8755616, datetime.date(1994, 6, 27))
1994-06-27
result is back for  (-96.7968559, 32.7762719, datetime.date(1994, 6, 27))
1994-06-28
result is back for  (-122.1598465, 37.4443293, datetime.date(1994, 6, 28))
1994-06-28
result is back for  (-77.0363849, 38.8950982, datetime.date(1994, 6, 28))
1994-06-28
result is back for  (-74.0970865, 40.833989, datetime.date(1994, 6, 28))
1994-06-28
result is back for  (-83.2910468, 42.6389216, datetime.date(1994, 6, 28))
1994-06-29
result is back for  (-81.379045, 28.5421218, datetime.date(1994, 6, 29))
1994-06-29
result is back for  (-77.0363849, 38.8950982, datetime.date(1994, 6, 29))
1994-07-02
result is back for  (-87.6244212, 41.8755616, datetime.date(1994, 7, 2))
1994-07-02
result is back for  (-77.0363849, 38.8950982, datetime.date(1994, 7, 2))
1994-07-03
result is back for  (-118.144155, 34.1476507, datetime.date(1994, 7, 3))
1994-07-03
result is back for  (-96.7968559, 32.7762719, datetime.date(1994, 7, 3))
1994-07-04
result is back for  (-81.379045, 28.5421218, datetime.date(1994, 7, 4))
1994-07-05
result is back for  (-71.2478308, 42.0653768, datetime.date(1994, 7, 5))
1994-07-05
result is back for  (-74.0970865, 40.833989, datetime.date(1994, 7, 5))
1994-07-09
result is back for  (-71.2478308, 42.0653768, datetime.date(1994, 7, 9))
1994-07-09
result is back for  (-96.7968559, 32.7762719, datetime.date(1994, 7, 9))
1994-07-10
result is back for  (-74.0970865, 40.833989, datetime.date(1994, 7, 10))
1994-07-10
result is back for  (-122.1598465, 37.4443293, datetime.date(1994, 7, 10))
1994-07-13
result is back for  (-74.0970865, 40.833989, datetime.date(1994, 7, 13))
1994-07-16
result is back for  (-118.144155, 34.1476507, datetime.date(1994, 7, 16))
1994-07-17
result is back for  (-118.144155, 34.1476507, datetime.date(1994, 7, 17))
1996-06-08
Cache hit for 51.5074456_-0.1277653_1996-06-08
1996-06-09
result is back for  (-1.4702278, 53.3806626, datetime.date(1996, 6, 9))
1996-06-09
result is back for  (-1.5437941, 53.7974185, datetime.date(1996, 6, 9))
1996-06-10
result is back for  (-1.6131572, 54.9738474, datetime.date(1996, 6, 10))
1996-06-10
result is back for  (-1.8518439, 52.4948994, datetime.date(1996, 6, 10))
1996-06-11
result is back for  (-2.9166389, 53.3933411, datetime.date(1996, 6, 11))
1996-06-13
result is back for  (-1.8518439, 52.4948994, datetime.date(1996, 6, 13))
1996-06-13
result is back for  (-1.6131572, 54.9738474, datetime.date(1996, 6, 13))
1996-06-15
result is back for  (-1.5437941, 53.7974185, datetime.date(1996, 6, 15))
1996-06-15
Cache hit for 51.5074456_-0.1277653_1996-06-15
1996-06-16
result is back for  (-2.2324547, 53.4424618, datetime.date(1996, 6, 16))
1996-06-18
result is back for  (-1.6131572, 54.9738474, datetime.date(1996, 6, 18))
1996-06-18
Cache hit for 51.5074456_-0.1277653_1996-06-18
1996-06-18
result is back for  (-1.5437941, 53.7974185, datetime.date(1996, 6, 18))
1996-06-18
result is back for  (-1.8518439, 52.4948994, datetime.date(1996, 6, 18))
1996-06-19
result is back for  (-1.1496461, 52.9534193, datetime.date(1996, 6, 19))
1996-06-19
result is back for  (-2.2324547, 53.4424618, datetime.date(1996, 6, 19))
1996-06-19
result is back for  (-2.9166389, 53.3933411, datetime.date(1996, 6, 19))
1996-06-19
result is back for  (-1.4702278, 53.3806626, datetime.date(1996, 6, 19))
1996-06-22
result is back for  (-2.9166389, 53.3933411, datetime.date(1996, 6, 22))
1996-06-22
Cache hit for 51.5074456_-0.1277653_1996-06-22
1996-06-23
result is back for  (-2.2324547, 53.4424618, datetime.date(1996, 6, 23))
1996-06-23
result is back for  (-1.8518439, 52.4948994, datetime.date(1996, 6, 23))
1996-06-26
Cache hit for 51.5074456_-0.1277653_1996-06-26
1996-06-26
result is back for  (-2.2324547, 53.4424618, datetime.date(1996, 6, 26))
1996-06-30
result is back for  (-0.1277653, 51.5074456, datetime.date(1996, 6, 30))
1998-06-10
result is back for  (3.8767337, 43.6112422, datetime.date(1998, 6, 10))
1998-06-10
result is back for  (2.3627508, 48.9383732, datetime.date(1998, 6, 10))
1998-06-11
result is back for  (1.4442433, 43.6044638, datetime.date(1998, 6, 11))
1998-06-11
result is back for  (-0.5800364, 44.841225, datetime.date(1998, 6, 11))
1998-06-12
result is back for  (3.8767337, 43.6112422, datetime.date(1998, 6, 12))
1998-06-12
result is back for  (2.8319805, 50.4291723, datetime.date(1998, 6, 12))
1998-06-13
result is back for  (-1.5541362, 47.2186371, datetime.date(1998, 6, 13))
1998-06-13
result is back for  (4.8320114, 45.7578137, datetime.date(1998, 6, 13))
1998-06-13
result is back for  (2.3627508, 48.9383732, datetime.date(1998, 6, 13))
1998-06-15
result is back for  (4.8320114, 45.7578137, datetime.date(1998, 6, 15))
1998-06-15
result is back for  (5.3777888, 43.2963986, datetime.date(1998, 6, 15))
1998-06-16
result is back for  (-1.5541362, 47.2186371, datetime.date(1998, 6, 16))
1998-06-16
result is back for  (-0.5800364, 44.841225, datetime.date(1998, 6, 16))
1998-06-17
result is back for  (4.3873058, 45.4401467, datetime.date(1998, 6, 17))
1998-06-17
result is back for  (3.8767337, 43.6112422, datetime.date(1998, 6, 17))
1998-06-18
result is back for  (2.3627508, 48.9383732, datetime.date(1998, 6, 18))
1998-06-19
result is back for  (2.3483915, 48.8534951, datetime.date(1998, 6, 19))
1998-06-19
result is back for  (4.3873058, 45.4401467, datetime.date(1998, 6, 19))
1998-06-20
result is back for  (-0.5800364, 44.841225, datetime.date(1998, 6, 20))
1998-06-20
result is back for  (5.3777888, 43.2963986, datetime.date(1998, 6, 20))
1998-06-22
result is back for  (3.8767337, 43.6112422, datetime.date(1998, 6, 22))
1998-06-22
result is back for  (1.4442433, 43.6044638, datetime.date(1998, 6, 22))
1998-06-23
result is back for  (2.3627508, 48.9383732, datetime.date(1998, 6, 23))
1998-06-23
result is back for  (-1.5541362, 47.2186371, datetime.date(1998, 6, 23))
1998-06-23
result is back for  (4.3873058, 45.4401467, datetime.date(1998, 6, 23))
1998-06-23
result is back for  (5.3777888, 43.2963986, datetime.date(1998, 6, 23))
1998-06-24
result is back for  (1.4442433, 43.6044638, datetime.date(1998, 6, 24))
1998-06-24
result is back for  (-0.5800364, 44.841225, datetime.date(1998, 6, 24))
1998-06-24
result is back for  (2.8319805, 50.4291723, datetime.date(1998, 6, 24))
1998-06-24
result is back for  (4.8320114, 45.7578137, datetime.date(1998, 6, 24))
1998-06-25
result is back for  (3.8767337, 43.6112422, datetime.date(1998, 6, 25))
1998-06-25
result is back for  (4.3873058, 45.4401467, datetime.date(1998, 6, 25))
1998-06-25
result is back for  (2.3483915, 48.8534951, datetime.date(1998, 6, 25))
1998-06-26
result is back for  (4.8320114, 45.7578137, datetime.date(1998, 6, 26))
1998-06-26
result is back for  (-0.5800364, 44.841225, datetime.date(1998, 6, 26))
1998-06-26
result is back for  (2.8319805, 50.4291723, datetime.date(1998, 6, 26))
1998-06-26
result is back for  (2.3627508, 48.9383732, datetime.date(1998, 6, 26))
1998-06-27
result is back for  (5.3777888, 43.2963986, datetime.date(1998, 6, 27))
1998-06-27
result is back for  (2.3483915, 48.8534951, datetime.date(1998, 6, 27))
1998-06-28
result is back for  (2.3627508, 48.9383732, datetime.date(1998, 6, 28))
1998-06-28
result is back for  (2.8319805, 50.4291723, datetime.date(1998, 6, 28))
1998-06-29
result is back for  (3.8767337, 43.6112422, datetime.date(1998, 6, 29))
1998-06-30
result is back for  (-0.5800364, 44.841225, datetime.date(1998, 6, 30))
1998-06-30
result is back for  (4.3873058, 45.4401467, datetime.date(1998, 6, 30))
1998-07-03
result is back for  (2.3627508, 48.9383732, datetime.date(1998, 7, 3))
1998-07-03
result is back for  (-1.5541362, 47.2186371, datetime.date(1998, 7, 3))
1998-07-04
result is back for  (4.8320114, 45.7578137, datetime.date(1998, 7, 4))
1998-07-04
result is back for  (5.3777888, 43.2963986, datetime.date(1998, 7, 4))
1998-07-07
result is back for  (5.3777888, 43.2963986, datetime.date(1998, 7, 7))
1998-07-08
result is back for  (2.3627508, 48.9383732, datetime.date(1998, 7, 8))
1998-07-11
result is back for  (2.3483915, 48.8534951, datetime.date(1998, 7, 11))
1998-07-12
result is back for  (2.3627508, 48.9383732, datetime.date(1998, 7, 12))
2000-06-19
result is back for  (5.478633, 51.4392648, datetime.date(2000, 6, 19))
2000-06-19
Cache hit for 50.8467372_4.352493_2000-06-19
2000-06-20
result is back for  (4.444528, 50.4116233, datetime.date(2000, 6, 20))
2000-06-20
result is back for  (4.47775, 51.9244424, datetime.date(2000, 6, 20))
2000-06-21
result is back for  (5.8762345, 52.0056642, datetime.date(2000, 6, 21))
2000-06-21
Cache hit for 52.3730796_4.8924534_2000-06-21
2000-06-21
result is back for  (5.5736112, 50.6450944, datetime.date(2000, 6, 21))
2000-06-24
result is back for  (4.8924534, 52.3730796, datetime.date(2000, 6, 24))
2000-06-24
result is back for  (4.352493, 50.8467372, datetime.date(2000, 6, 24))
2000-06-25
result is back for  (3.226772, 51.2085526, datetime.date(2000, 6, 25))
2000-06-28
result is back for  (4.352493, 50.8467372, datetime.date(2000, 6, 28))
2000-06-29
Cache hit for 52.3730796_4.8924534_2000-06-29
2000-07-02
result is back for  (4.47775, 51.9244424, datetime.date(2000, 7, 2))
2002-06-01
result is back for  (129.3119136, 35.5391697, datetime.date(2002, 6, 1))
2002-06-01
result is back for  (141.3542924, 43.061936, datetime.date(2002, 6, 1))
2002-06-02
result is back for  (140.6450292, 35.9661164, datetime.date(2002, 6, 2))
2002-06-02
result is back for  (126.8306362, 35.1558147, datetime.date(2002, 6, 2))
2002-06-02
result is back for  (129.0752365, 35.1799528, datetime.date(2002, 6, 2))
2002-06-02
result is back for  (139.4160114, 35.9754168, datetime.date(2002, 6, 2))
2002-06-03
result is back for  (129.3119136, 35.5391697, datetime.date(2002, 6, 3))
2002-06-04
result is back for  (139.4160114, 35.9754168, datetime.date(2002, 6, 4))
2002-06-06
result is back for  (129.0752365, 35.1799528, datetime.date(2002, 6, 6))
2002-06-06
result is back for  (139.4160114, 35.9754168, datetime.date(2002, 6, 6))
2002-06-07
result is back for  (141.3542924, 43.061936, datetime.date(2002, 6, 7))
2002-06-07
result is back for  (135.1943764, 34.6932379, datetime.date(2002, 6, 7))
2002-06-07
result is back for  (127.1472805, 35.8237631, datetime.date(2002, 6, 7))
2002-06-08
result is back for  (128.6018, 35.8713, datetime.date(2002, 6, 8))
2002-06-09
result is back for  (126.7052, 37.456, datetime.date(2002, 6, 9))
2002-06-10
result is back for  (131.4270217, 33.1819875, datetime.date(2002, 6, 10))
2002-06-11
result is back for  (126.7052, 37.456, datetime.date(2002, 6, 11))
2002-06-11
result is back for  (137.9246962, 34.7501492, datetime.date(2002, 6, 11))
2002-06-11
result is back for  (139.6343802, 35.4503381, datetime.date(2002, 6, 11))
2002-06-11
result is back for  (127.0287472, 37.2633325, datetime.date(2002, 6, 11))
2002-06-12
result is back for  (127.3849016, 36.3497007, datetime.date(2002, 6, 12))
2002-06-12
result is back for  (126.5610278, 33.252845, datetime.date(2002, 6, 12))
2002-06-12
result is back for  (140.9753442, 38.3301406, datetime.date(2002, 6, 12))
2002-06-12
result is back for  (135.5014539, 34.6937569, datetime.date(2002, 6, 12))
2002-06-13
result is back for  (127.0287472, 37.2633325, datetime.date(2002, 6, 13))
2002-06-13
result is back for  (126.9782914, 37.5666791, datetime.date(2002, 6, 13))
2002-06-13
result is back for  (139.6343802, 35.4503381, datetime.date(2002, 6, 13))
2002-06-13
result is back for  (131.4270217, 33.1819875, datetime.date(2002, 6, 13))
2002-06-14
result is back for  (126.7052, 37.456, datetime.date(2002, 6, 14))
2002-06-14
result is back for  (137.9246962, 34.7501492, datetime.date(2002, 6, 14))
2002-06-14
result is back for  (135.5014539, 34.6937569, datetime.date(2002, 6, 14))
2002-06-15
result is back for  (138.7669125, 37.6452283, datetime.date(2002, 6, 15))
2002-06-15
result is back for  (126.5610278, 33.252845, datetime.date(2002, 6, 15))
2002-06-16
result is back for  (127.0287472, 37.2633325, datetime.date(2002, 6, 16))
2002-06-16
result is back for  (131.4270217, 33.1819875, datetime.date(2002, 6, 16))
2002-06-17
result is back for  (135.1943764, 34.6932379, datetime.date(2002, 6, 17))
2002-06-18
result is back for  (140.9753442, 38.3301406, datetime.date(2002, 6, 18))
2002-06-18
result is back for  (127.3849016, 36.3497007, datetime.date(2002, 6, 18))
2002-06-21
result is back for  (137.9246962, 34.7501492, datetime.date(2002, 6, 21))
2002-06-22
result is back for  (126.8306362, 35.1558147, datetime.date(2002, 6, 22))
2002-06-22
result is back for  (135.5014539, 34.6937569, datetime.date(2002, 6, 22))
2002-06-25
Cache hit for 37.5666791_126.9782914_2002-06-25
2002-06-26
result is back for  (139.4160114, 35.9754168, datetime.date(2002, 6, 26))
2002-06-29
result is back for  (128.6018, 35.8713, datetime.date(2002, 6, 29))
2002-06-30
result is back for  (139.6343802, 35.4503381, datetime.date(2002, 6, 30))
2004-06-20
Cache hit for 38.7077507_-9.1365919_2004-06-20
2004-06-20
result is back for  (-7.935182, 37.0162944, datetime.date(2004, 6, 20))
2004-06-21
result is back for  (-9.1365919, 38.7077507, datetime.date(2004, 6, 21))
2004-06-21
result is back for  (-8.4294632, 40.2111931, datetime.date(2004, 6, 21))
2004-06-22
result is back for  (-8.2955712, 41.4417677, datetime.date(2004, 6, 22))
2004-06-22
result is back for  (-8.6103497, 41.1502195, datetime.date(2004, 6, 22))
2004-06-23
result is back for  (-9.1365919, 38.7077507, datetime.date(2004, 6, 23))
2004-06-23
result is back for  (-8.4280045, 41.5510583, datetime.date(2004, 6, 23))
2004-06-24
Cache hit for 38.7077507_-9.1365919_2004-06-24
2004-06-25
result is back for  (-9.1365919, 38.7077507, datetime.date(2004, 6, 25))
2004-06-26
result is back for  (-7.935182, 37.0162944, datetime.date(2004, 6, 26))
2004-06-27
result is back for  (-8.6103497, 41.1502195, datetime.date(2004, 6, 27))
2004-06-30
Cache hit for 38.7077507_-9.1365919_2004-06-30
2004-07-01
result is back for  (-8.6103497, 41.1502195, datetime.date(2004, 7, 1))
2004-07-04
Cache hit for 38.7077507_-9.1365919_2004-07-04
2006-06-20
Cache hit for 52.5173885_13.3951309_2006-06-20
2006-06-20
result is back for  (6.959974, 50.938361, datetime.date(2006, 6, 20))
2006-06-20
result is back for  (9.7385532, 52.3744779, datetime.date(2006, 6, 20))
2006-06-20
result is back for  (7.7689951, 49.4432174, datetime.date(2006, 6, 20))
2006-06-21
result is back for  (7.0960124, 51.5110321, datetime.date(2006, 6, 21))
2006-06-21
result is back for  (12.3747329, 51.3406321, datetime.date(2006, 6, 21))
2006-06-21
result is back for  (8.6820917, 50.1106444, datetime.date(2006, 6, 21))
2006-06-22
result is back for  (9.1800132, 48.7784485, datetime.date(2006, 6, 22))
2006-06-22
result is back for  (7.4652789, 51.5142273, datetime.date(2006, 6, 22))
2006-06-22
result is back for  (10.0013165, 53.5501721, datetime.date(2006, 6, 22))
2006-06-23
result is back for  (13.3951309, 52.5173885, datetime.date(2006, 6, 23))
2006-06-23
result is back for  (7.7689951, 49.4432174, datetime.date(2006, 6, 23))
2006-06-23
result is back for  (6.959974, 50.938361, datetime.date(2006, 6, 23))
2006-06-23
result is back for  (9.7385532, 52.3744779, datetime.date(2006, 6, 23))
2006-06-24
result is back for  (12.3747329, 51.3406321, datetime.date(2006, 6, 24))
2006-06-24
result is back for  (11.5753822, 48.1371079, datetime.date(2006, 6, 24))
2006-06-25
result is back for  (9.1800132, 48.7784485, datetime.date(2006, 6, 25))
2006-06-25
result is back for  (11.077298, 49.453872, datetime.date(2006, 6, 25))
2006-06-26
result is back for  (7.7689951, 49.4432174, datetime.date(2006, 6, 26))
2006-06-26
result is back for  (6.959974, 50.938361, datetime.date(2006, 6, 26))
2006-06-27
result is back for  (7.4652789, 51.5142273, datetime.date(2006, 6, 27))
2006-06-27
result is back for  (9.7385532, 52.3744779, datetime.date(2006, 6, 27))
2006-06-30
Cache hit for 52.5173885_13.3951309_2006-06-30
2006-06-30
result is back for  (10.0013165, 53.5501721, datetime.date(2006, 6, 30))
2006-07-01
result is back for  (8.6820917, 50.1106444, datetime.date(2006, 7, 1))
2006-07-01
result is back for  (7.0960124, 51.5110321, datetime.date(2006, 7, 1))
2006-07-04
result is back for  (7.4652789, 51.5142273, datetime.date(2006, 7, 4))
2006-07-05
result is back for  (11.5753822, 48.1371079, datetime.date(2006, 7, 5))
2006-07-08
result is back for  (9.1800132, 48.7784485, datetime.date(2006, 7, 8))
2006-07-09
result is back for  (13.3951309, 52.5173885, datetime.date(2006, 7, 9))
2008-06-15
result is back for  (6.1466014, 46.2017559, datetime.date(2008, 6, 15))
2008-06-15
result is back for  (7.5878261, 47.5581077, datetime.date(2008, 6, 15))
2008-06-16
result is back for  (14.3075976, 46.623943, datetime.date(2008, 6, 16))
2008-06-16
Cache hit for 48.2083537_16.3725042_2008-06-16
2008-06-17
result is back for  (8.5410422, 47.3744489, datetime.date(2008, 6, 17))
2008-06-17
result is back for  (7.4521749, 46.9484742, datetime.date(2008, 6, 17))
2008-06-18
result is back for  (13.0464806, 47.7981346, datetime.date(2008, 6, 18))
2008-06-18
result is back for  (11.3927685, 47.2654296, datetime.date(2008, 6, 18))
2008-06-19
result is back for  (7.5878261, 47.5581077, datetime.date(2008, 6, 19))
2008-06-20
result is back for  (16.3725042, 48.2083537, datetime.date(2008, 6, 20))
2008-06-21
result is back for  (7.5878261, 47.5581077, datetime.date(2008, 6, 21))
2008-06-22
result is back for  (16.3725042, 48.2083537, datetime.date(2008, 6, 22))
2008-06-25
result is back for  (7.5878261, 47.5581077, datetime.date(2008, 6, 25))
2008-06-26
result is back for  (16.3725042, 48.2083537, datetime.date(2008, 6, 26))
2008-06-29
result is back for  (16.3725042, 48.2083537, datetime.date(2008, 6, 29))
2010-06-22
result is back for  (31.009909, -29.861825, datetime.date(2010, 6, 22))
2010-06-22
result is back for  (27.241448, -25.665655, datetime.date(2010, 6, 22))
2010-06-22
result is back for  (29.4613889, -23.9058333, datetime.date(2010, 6, 22))
2010-06-22
result is back for  (26.215496, -29.116395, datetime.date(2010, 6, 22))
2010-06-23
result is back for  (28.049722, -26.205, datetime.date(2010, 6, 23))
2010-06-23
result is back for  (30.9772719, -25.4729094, datetime.date(2010, 6, 23))
2010-06-23
result is back for  (25.6186731, -33.9618598, datetime.date(2010, 6, 23))
2010-06-24
result is back for  (28.049722, -26.205, datetime.date(2010, 6, 24))
2010-06-24
result is back for  (27.241448, -25.665655, datetime.date(2010, 6, 24))
2010-06-24
result is back for  (18.4172197, -33.9288301, datetime.date(2010, 6, 24))
2010-06-24
result is back for  (29.4613889, -23.9058333, datetime.date(2010, 6, 24))
2010-06-25
result is back for  (31.009909, -29.861825, datetime.date(2010, 6, 25))
2010-06-25
result is back for  (26.215496, -29.116395, datetime.date(2010, 6, 25))
2010-06-25
result is back for  (30.9772719, -25.4729094, datetime.date(2010, 6, 25))
2010-06-25
result is back for  (28.1879101, -25.7459277, datetime.date(2010, 6, 25))
2010-06-26
result is back for  (25.6186731, -33.9618598, datetime.date(2010, 6, 26))
2010-06-27

In [257]:
result["home_stadium_temp_max"] = np.abs(result['home_temperature_max'] - result['stadium_temperature_max'])
result["home_stadium_temp_min"] = np.abs(result['home_temperature_min'] - result['stadium_temperature_min'])
result["home_stadium_temp_avg"] = (result['home_stadium_temp_max'] + result['home_stadium_temp_min']) / 2

result["away_stadium_temp_max"] = np.abs(result['away_temperature_max'] - result['stadium_temperature_max'])
result["away_stadium_temp_min"] = np.abs(result['away_temperature_min'] - result['stadium_temperature_min'])
result["away_stadium_temp_avg"] = (result['away_stadium_temp_max'] + result['away_stadium_temp_min']) / 2

In [258]:
result.to_csv("../data/processed/matches.csv", index=False)